In [5]:
import os

unzip_destination = '/content/'

print(f"Listing files in {unzip_destination}:")
for root, dirs, files in os.walk(unzip_destination):
    for file in files:
        print(os.path.join(root, file))

Listing files in /content/:
/content/Dataset.zip
/content/.config/.last_survey_prompt.yaml
/content/.config/config_sentinel
/content/.config/gce
/content/.config/.last_opt_in_prompt.yaml
/content/.config/active_config
/content/.config/default_configs.db
/content/.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
/content/.config/.last_update_check.json
/content/.config/logs/2025.10.10/13.35.51.839716.log
/content/.config/logs/2025.10.10/13.36.01.945525.log
/content/.config/logs/2025.10.10/13.36.10.325401.log
/content/.config/logs/2025.10.10/13.36.11.036806.log
/content/.config/logs/2025.10.10/13.35.31.347850.log
/content/.config/logs/2025.10.10/13.36.00.745649.log
/content/.config/configurations/config_default
/content/sample_data/anscombe.json
/content/sample_data/README.md
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_train.csv

In [4]:
import os

zip_file_path = '/content/Dataset.zip'
unzip_destination = '/content/'

if os.path.exists(zip_file_path):
    print(f"Unzipping {zip_file_path} to {unzip_destination}...")
    os.system(f'unzip {zip_file_path} -d {unzip_destination}')
    print("Unzipping complete.")
else:
    print(f"File not found: {zip_file_path}. Cannot unzip.")

Unzipping /content/Dataset.zip to /content/...
Unzipping complete.

In [3]:
import os

file_path = '/content/Dataset.zip'

if os.path.exists(file_path):
    print(f"File found: {file_path}")
    # Attempt to unzip the file to check for corruption
    try:
        os.system(f'unzip -t {file_path}')
        print("File seems to be a valid zip file.")
    except Exception as e:
        print(f"Error testing zip file: {e}")
else:
    print(f"File not found: {file_path}")

File found: /content/Dataset.zip
File seems to be a valid zip file.

## Summary:

### Data Analysis Key Findings

*   The initial attempt to use a provided `Dataset.zip` for data acquisition failed as it did not contain the necessary satellite imagery or weather data.
*   The project proceeded by simulating data using `xarray` for satellite imagery (MODIS) and `pandas` for weather data (NOAA). This simulation included creating placeholder data for red and near-infrared bands, temperature, precipitation, and historical fire occurrences.
*   Key preprocessing steps were simulated, including the calculation of the Normalized Difference Vegetation Index (NDVI) from the simulated satellite bands. The necessity of real-world steps like atmospheric correction, georeferencing, and spatio-temporal interpolation of weather data was acknowledged.
*   Feature engineering involved adding simulated historical fire data and a derived simulated fuel moisture index to the dataset. The critical absence of topography data and other weather variables like wind and humidity was noted.
*   The simulated spatio-temporal dataset was converted into a tabular format (DataFrame) by stacking spatial dimensions for compatibility with standard machine learning models like `scikit-learn`.
*   The tabular data was split into simulated training (70%), validation (15%), and test (15%) sets using `train_test_split`.
*   A Random Forest Classifier was chosen, trained on the simulated training data, and subsequently retrained on the combined training and validation data.
*   Model performance was evaluated on the simulated test set using standard classification metrics: Precision ({precision:.4f}), Recall ({recall:.4f}), F1-Score ({f1:.4f}), AUC-ROC ({auc_roc:.4f}), and False Alarm Rate ({false_alarm_rate:.4f}). These metrics are based on simulated data and likely do not reflect real-world performance.
*   The inability to calculate spatial and temporal accuracy metrics due to the data splitting method (flattening spatio-temporal dimensions) was a significant limitation highlighted during evaluation.
*   The retrained model was successfully used to predict wildfire risk probabilities on simulated new data, demonstrating the prediction step of the workflow.
*   The entire simulated process, from data sources to prediction and evaluation limitations, was documented as a blueprint for a real-world implementation.

### Insights or Next Steps

*   A crucial next step for a real-world application is to obtain actual satellite imagery (MODIS, FIRMS), weather data (NOAA), and topography data for the target region and implement robust preprocessing pipelines including atmospheric correction, georeferencing, and accurate spatio-temporal interpolation.
*   Future model development should explore techniques and data structures (e.g., using `xarray` more fully, or specialized geospatial libraries) that preserve the spatio-temporal relationships in the data, enabling the calculation of spatial and temporal accuracy metrics and potentially leveraging spatial/temporal dependencies in the modeling process itself (e.g., Spatio-Temporal models, CNN-LSTM hybrids).

## Reporting

### Subtask:
Document the entire process, including data sources, preprocessing steps, model details, evaluation results, and insights gained.

**Reasoning**:
Document the entire process as requested in the subtask instructions, summarizing the steps performed and the insights gained based on the available variables and the context of simulated data.

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import xarray as xr

# Add the code from cell 639deeb1 here
# Step 1: Simulate loading satellite imagery (MODIS) using xarray DataArray
# In a real scenario, you would use xr.open_dataset() or similar functions
# to load data from downloaded HDF or GeoTIFF files.
print("Simulating loading satellite imagery...")
# Create a placeholder DataArray representing MODIS imagery (e.g., Red and NIR bands)
# with dimensions for time, latitude, and longitude.
time_coords = pd.date_range('2022-01-01', periods=10, freq='D')
lat_coords = np.linspace(32, 42, 100) # Example latitude range for California
lon_coords = np.linspace(-124, -114, 150) # Example longitude range for California

# Create dummy data for Red and NIR bands
red_band_data = np.random.rand(10, 100, 150) * 0.3 + 0.1 # Example reflectance values
nir_band_data = np.random.rand(10, 100, 150) * 0.5 + 0.3 # Example reflectance values

modis_ds = xr.Dataset({
    'red': (['time', 'latitude', 'longitude'], red_band_data),
    'nir': (('time', 'latitude', 'longitude'), nir_band_data)
}, coords={'time': time_coords, 'latitude': lat_coords, 'longitude': lon_coords})

print("Simulated MODIS imagery Dataset:")
display(modis_ds)

# Step 1: Simulate loading weather data (NOAA) using pandas DataFrame
# In a real scenario, you would use pd.read_csv() or similar functions
# to load data from downloaded CSV files.
print("\nSimulating loading weather data...")
# Create a placeholder DataFrame representing weather data from multiple stations
# with columns for time, latitude, longitude, temperature, and precipitation.
weather_data = {
    'time': pd.to_datetime(np.random.choice(time_coords, 50)),
    'latitude': np.random.uniform(32, 42, 50),
    'longitude': np.random.uniform(-124, -114, 50),
    'temperature': np.random.uniform(0, 30, 50), # Example temperature in Celsius
    'precipitation': np.random.uniform(0, 10, 50) # Example precipitation in mm
}
weather_df = pd.DataFrame(weather_data)

print("Simulated NOAA weather DataFrame:")
display(weather_df.head())


# Step 3: Calculate relevant vegetation indices (NDVI) from the simulated satellite imagery
print("\nCalculating NDVI...")
# NDVI = (NIR - Red) / (NIR + Red)
# Ensure no division by zero by adding a small epsilon or handling NaNs
ndvi = (modis_ds['nir'] - modis_ds['red']) / (modis_ds['nir'] + modis_ds['red'] + 1e-9)
modis_ds['ndvi'] = ndvi

print("Added NDVI to MODIS Dataset:")
display(modis_ds)

# Step 4: Clean and format the weather data (Simulated)
# In a real scenario, this would involve handling missing values (e.g., imputation),
# standardizing column names, correcting data types, etc.
print("\nSimulating cleaning and formatting weather data...")
# For this simulation, we assume the data is already reasonably clean.
# A simple step like dropping potential NaNs could be done:
weather_df_cleaned = weather_df.dropna()

print("Simulated cleaned weather DataFrame:")
display(weather_df_cleaned.head())

# Step 5: Interpolate weather data spatially and temporally to match the satellite imagery resolution (Simulated)
# This is a complex step in a real scenario, often involving spatial interpolation
# techniques (e.g., inverse distance weighting, kriging) and temporal interpolation.
# For simulation purposes, we'll skip the actual interpolation and acknowledge the need.
print("\nAcknowledging the need for spatial and temporal interpolation of weather data...")
print("In a real scenario, weather data would be interpolated to match the time, latitude, and longitude grid of the satellite imagery.")
# The result would ideally be an xarray DataArray or Dataset with the same dimensions as modis_ds.
# Let's create a placeholder for the interpolated weather data with the same dimensions as modis_ds
interpolated_weather_ds = xr.Dataset({
    'temperature': (['time', 'latitude', 'longitude'], np.random.uniform(0, 30, size=modis_ds['red'].shape)),
    'precipitation': ((['time', 'latitude', 'longitude']), np.random.uniform(0, 10, size=modis_ds['red'].shape))
}, coords=modis_ds.coords)

print("Simulated interpolated weather Dataset:")
display(interpolated_weather_ds)


# Step 6: Integrate the processed satellite imagery and interpolated weather data into a unified dataset (Simulated)
print("\nIntegrating satellite imagery and weather data...")
# Combine the two xarray Datasets. Assuming they have the same dimensions and coordinates.
unified_ds = xr.merge([modis_ds, interpolated_weather_ds])

print("Unified Dataset:")
display(unified_ds)

# Step 2: Perform atmospheric correction and georeferencing (Acknowledged)
print("\nAcknowledging the need for atmospheric correction and georeferencing...")
print("In a real scenario, atmospheric correction would be applied to satellite imagery to remove atmospheric effects, and georeferencing would ensure accurate spatial alignment.")
# These steps are highly dependent on the specific data product and require specialized libraries
# or tools (e.g., GDAL, rasterio, or specific remote sensing software), which are not
# straightforward to demonstrate with placeholder data in this environment.

# Add the code from cell 2abfa1f3 here
print("Simulating topography (elevation, slope, aspect), wind speed, and humidity...")

# Simulate Elevation (example: a simple gradient or random noise)
# Real elevation would come from a DEM and be static over time.
# For simulation, we'll create a static 2D field and expand it over time.
elevation_data_2d = np.random.uniform(100, 3000, size=(unified_ds.sizes['latitude'], unified_ds.sizes['longitude']))
elevation_data = np.repeat(elevation_data_2d[np.newaxis, :, :], unified_ds.sizes['time'], axis=0)
unified_ds['elevation'] = (('time', 'latitude', 'longitude'), elevation_data)

# Simulate Slope and Aspect (derived from elevation in reality)
# For simulation, we'll just create random data.
# Slope: 0-90 degrees
slope_data = np.random.uniform(0, 45, size=unified_ds['elevation'].shape)
unified_ds['slope'] = (('time', 'latitude', 'longitude'), slope_data)

# Aspect: 0-360 degrees
aspect_data = np.random.uniform(0, 360, size=unified_ds['elevation'].shape)
unified_ds['aspect'] = (('time', 'latitude', 'longitude'), aspect_data)

# Simulate Wind Speed (example: random positive values)
wind_speed_data = np.random.uniform(0, 30, size=unified_ds['elevation'].shape) # knots or m/s
unified_ds['wind_speed'] = (('time', 'latitude', 'longitude'), wind_speed_data)

# Simulate Humidity (example: random values between 0 and 100)
humidity_data = np.random.uniform(20, 100, size=unified_ds['elevation'].shape) # percentage
unified_ds['humidity'] = (('time', 'latitude', 'longitude'), humidity_data)

print("Simulated topography, wind speed, and humidity added to unified Dataset.")

# Display the updated structure of the unified_ds
print("\nUpdated unified Dataset structure:")
display(unified_ds)


# Add the code from cell mI2m0FnH4N9Z here
# Step 2: Simulate adding historical fire data as a new data variable to unified_ds.
print("Simulating adding historical fire data...")
# Create a placeholder data variable for historical fire occurrences.
# This could be a binary mask (0 for no fire, 1 for fire) or fire radiative power.
# We'll create a binary mask with some random fire occurrences.
fire_history_data = np.random.randint(0, 2, size=unified_ds['red'].shape)
unified_ds['fire_history'] = (('time', 'latitude', 'longitude'), fire_history_data)

print("Added historical fire data to unified Dataset.")

# Step 3: Acknowledge that topography data is crucial but not available.
print("\nAcknowledging the importance of topography data...")
print("Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.")
print("Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.")
print("This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.")

# Step 4: Derive a simulated fuel moisture index.
print("\nDeriving a simulated fuel moisture index...")
# Create a simplified placeholder calculation based on temperature and precipitation.
# A real fuel moisture model is complex and depends on various factors.
# This is a simple inverse relationship with temperature and direct with precipitation.
# Ensure no division by zero or undefined behavior with extreme values.
# Adding a small constant to the denominator and scaling to a plausible range (e.g., 0 to 100)
simulated_fuel_moisture = (unified_ds['precipitation'] * 10) / (unified_ds['temperature'] + 1 + 1e-9)
# Clip values to a reasonable range, e.g., 0 to 100 for a percentage-like index
simulated_fuel_moisture = np.clip(simulated_fuel_moisture, 0, 100)
# Extract the data using .data property as required by the error
unified_ds['simulated_fuel_moisture'] = (('time', 'latitude', 'longitude'), simulated_fuel_moisture.data)

print("Added simulated fuel moisture index to unified Dataset.")

# Step 5: Acknowledge other potentially relevant features.
print("\nAcknowledging other important features not present...")
print("Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.")

# Step 6: Ensure the newly engineered features are added as data variables to the unified_ds.
# This was done in steps 2 and 4 by assigning new data variables to unified_ds.

# Step 7: Display the structure of the updated unified_ds.
print("\nUpdated unified Dataset structure:")
display(unified_ds)

# Add the code from cell 5c240199 here
# Define features (X) and target (y)
# The target variable is 'fire_history'.
# Features are the remaining relevant variables.
features = ['red', 'nir', 'ndvi', 'temperature', 'precipitation', 'simulated_fuel_moisture', 'elevation', 'slope', 'aspect', 'wind_speed', 'humidity']
target = 'fire_history'

# Convert the xarray Dataset to a pandas DataFrame for easier handling with train_test_split
# We will stack the spatial dimensions (latitude, longitude) to treat each grid cell at each time step as a sample.
# This assumes a modeling approach where each time-location snapshot is an independent sample.
unified_df = unified_ds.to_dataframe().reset_index()

# Drop the 'time', 'latitude', and 'longitude' columns from features for splitting,
# as these define the sample index after stacking.
X = unified_df[features]
y = unified_df[target]

# Split the data into training and a temporary set (validation + test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Split the temporary set into validation and test sets
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

# Print the shapes of the resulting sets
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_val:", X_val.shape)
print("Shape of y_val:", y_val.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

# Add the code from cell 2a84032c here
# 1. Combine training and validation data
X_train_combined = pd.concat([X_train, X_val])
y_train_combined = pd.concat([y_train, y_val])

# Train the Random Forest Classifier model on the combined data
print("Retraining the Random Forest model on combined training and validation data...")
retrained_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
retrained_model.fit(X_train_combined, y_train_combined)
print("Retraining complete.")

# 2. Make predictions on the test set
print("Making predictions on the test set...")
y_test_pred_class = retrained_model.predict(X_test)
y_test_pred_proba = retrained_model.predict_proba(X_test)[:, 1] # Probability of the positive class (fire=1)
print("Predictions complete.")

# 3. Calculate evaluation metrics on the test set
print("\nCalculating evaluation metrics on the test set...")
precision = precision_score(y_test, y_test_pred_class)
recall = recall_score(y_test, y_test_pred_class)
f1 = f1_score(y_test, y_test_pred_class)
auc_roc = roc_auc_score(y_test, y_test_pred_proba)

# Calculate False Alarm Rate
conf_matrix = confusion_matrix(y_test, y_test_pred_class)
# conf_matrix structure: [[TN, FP], [FN, TP]]
TN, FP, FN, TP = conf_matrix.ravel()
false_alarm_rate = FP / (FP + TN)
print("Evaluation metrics calculated.")

# 4. Print the calculated evaluation metrics for the test set
print("\n--- Model Evaluation Metrics (Test Set) ---")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"AUC-ROC: {auc_roc:.4f}")
print(f"False Alarm Rate: {false_alarm_rate:.4f}")
print("-----------------------------------------")

# 1. Summarize Data Sources
print("## 1. Data Sources")
print("Due to the lack of direct access to real-world satellite imagery (MODIS, FIRMS) and environmental data (NOAA), the data used in this project was simulated.")
print("- **MODIS/FIRMS Simulation:** Simulated raster data for 'red' and 'nir' bands were created using `xarray` with defined time, latitude, and longitude dimensions. Historical fire data was also simulated as a binary raster.")
print("- **NOAA Data Simulation:** Simulated point data for 'temperature' and 'precipitation' were created using `pandas` DataFrames with time, latitude, and longitude columns.")
print("- **Topography, Wind, Humidity Simulation:** Simulated raster data for 'elevation', 'slope', 'aspect', 'wind_speed', and 'humidity' were created and added to the `xarray` dataset.")
print("It's important to note that these simulations do not capture the complexity, spatial heterogeneity, or temporal dynamics of real satellite and weather data.")
print("-" * 50)

# 2. Detail Data Preprocessing Steps
print("## 2. Data Preprocessing Steps")
print("The preprocessing steps were simulated to mimic a real-world workflow:")
print("- **Simulated Loading and Cleaning:** Placeholder data structures (`xarray.Dataset` and `pandas.DataFrame`) were created to represent the raw data. Basic cleaning like dropping NaNs was mentioned but not extensively performed on the simulated data.")
print("- **NDVI Calculation:** The Normalized Difference Vegetation Index (NDVI) was calculated from the simulated 'red' and 'nir' bands using the standard formula.")
print("- **Atmospheric Correction and Georeferencing:** These crucial steps for real satellite imagery were acknowledged as necessary but not performed due to the simulated nature of the data. They would ensure accurate reflectance values and spatial alignment.")
print("- **Simulated Weather Data Interpolation:** The need to interpolate point-based weather data (temperature, precipitation) to match the raster grid and time steps of the satellite imagery was acknowledged. A simulated interpolated weather dataset with the same dimensions as the imagery was created.")
print("- **Data Integration:** The simulated satellite imagery (including NDVI) and the simulated interpolated weather data, along with simulated topography, wind, and humidity, were merged into a single `xarray.Dataset` for unified handling.")
print("-" * 50)

# 3. Describe Feature Engineering Process
print("## 3. Feature Engineering Process")
print("Features were engineered or included based on common practices in wildfire prediction:")
print("- **Simulated Historical Fire Data:** A binary raster representing historical fire occurrences was simulated and added as a feature. This serves as a proxy for past fire activity, which is often a strong predictor.")
print("- **Derived Simulated Fuel Moisture Index:** A simplified fuel moisture index was derived from the simulated temperature and precipitation data. This simulation used a basic formula and does not represent a scientifically accurate fuel moisture model. The importance of real fuel moisture models was noted.")
print("- **Simulated Topography, Wind, and Humidity:** Simulated data for elevation, slope, aspect, wind speed, and humidity were generated and added as features.")
print("-" * 50)

# 4. Explain Data Splitting Methodology
print("## 4. Data Splitting Methodology")
print("The unified dataset was converted from an xarray Dataset to a pandas DataFrame by stacking the spatial dimensions (latitude and longitude), treating each grid cell at each time step as a sample.")
print("The data was then split into training, validation, and test sets using `sklearn.model_selection.train_test_split`:")
print(f"- **Initial Split:** 70% Training, 30% Temporary (Validation + Test)")
print(f"- **Second Split:** The 30% temporary set was further split into 50% Validation and 50% Test, resulting in approximately 15% Validation and 15% Test sets relative to the original data.")
print("A `random_state` was used to ensure reproducibility of the splits.")
print("-" * 50)

# 5. Provide Model Details and Training Process
print("## 5. Model Details and Training Process")
print("- **Model Choice:** A Random Forest Classifier (`sklearn.ensemble.RandomForestClassifier`) was chosen for this binary classification task, suitable for predicting the probability of fire occurrence.")
print("- **Parameters:** The model was instantiated with `n_estimators=100` (number of trees in the forest) and `random_state=42` for reproducibility. `n_jobs=-1` was used to utilize all available CPU cores for faster training speed.")
print("- **Training Process:**")
print("  - The model was initially trained on the `X_train` and `y_train` sets.")
print("  - Following evaluation, the model was retrained on the combined `X_train_combined` and `y_train_combined` sets (training + validation data) for the final evaluation on the test set and prediction on new data.")
print("-" * 50)

# 6. Present Evaluation Results and Limitations
print("## 6. Evaluation Results and Limitations")
print("The model's performance was evaluated using standard classification metrics on both the validation and test sets.")
print(f"The metrics obtained on the **Test Set** were:")
print(f"- Precision: {precision:.4f}")
print(f"- Recall: {recall:.4f}")
print(f"- F1-Score: {f1:.4f}")
print(f"- AUC-ROC: {auc_roc:.4f}")
print(f"- False Alarm Rate: {false_alarm_rate:.4f}")
print("\n**Limitations:**")
print("- **Spatial and Temporal Accuracy:** Due to the data splitting method that flattened the spatial and temporal dimensions, specific spatial accuracy (e.g., correctly predicting fire location) and temporal accuracy (e.g., predicting fire timing) metrics could not be calculated in this workflow.")
print("- **Simulated Data:** The metrics are based on simulated data, which may not reflect the model's performance on real-world data. The simulated features and target variable lack the complexity and real-world relationships present in actual wildfire datasets.")
print("-" * 50)

# 7. Summarize Wildfire Risk Prediction Step
print("## 7. Wildfire Risk Prediction on New Data")
print("The retrained model was used to predict wildfire risk probabilities on simulated new data.")
# Define n_new_samples here
n_new_samples = 100
print(f"- **New Data Simulation:** A DataFrame (`X_new`) with {n_new_samples} samples was simulated, containing the same features as the training data ('red', 'nir', 'temperature', 'precipitation', 'simulated_fuel_moisture', 'elevation', 'slope', 'aspect', 'wind_speed', 'humidity').")
print("- **Preprocessing:** NDVI was calculated for the simulated new data to ensure consistency with the training data features.")
print("- **Prediction:** The `retrained_model.predict_proba()` method was used to obtain the probability of fire occurrence for each sample in the simulated new data.")
print("The predicted probabilities were added as a new column ('predicted_fire_probability') to the `X_new` DataFrame.")
print("-" * 50)

# 8. Discuss Key Insights Gained
print("## 8. Key Insights Gained")
print("Even with simulated data, the process highlighted several key aspects:")
print("- **Workflow Demonstration:** The exercise successfully demonstrated the end-to-end workflow of a machine learning project for environmental prediction, from data simulation and preprocessing to model training, evaluation, and prediction.")
print("- **Feature Importance (Implicit):** While not explicitly analyzed, the chosen features (simulated satellite bands, NDVI, temperature, precipitation, fuel moisture, historical fire, topography, wind, humidity) represent commonly used indicators for wildfire risk, reinforcing their potential relevance in a real model.")
print("- **Data Preparation Challenges:** The simulation underscored the complexity of preparing real-world geospatial and temporal data, particularly atmospheric correction, georeferencing, and spatio-temporal interpolation.")
print("- **Evaluation Nuances:** The limitation in calculating spatial and temporal accuracy highlighted the importance of data structure and splitting strategies when working with spatio-temporal data.")
print("- **Model Applicability:** A Random Forest Classifier, or similar tree-based models, are suitable baseline models for this type of tabular prediction task once the data is prepared.")
print("-" * 50)

# 9. Outline Potential Next Steps for Real-World Implementation
print("## 9. Potential Next Steps for Real-World Implementation")
print("To transition this project towards a real-world application, the following steps would be crucial:")
print("- **Obtain Actual Data:** Secure access to and download real MODIS/FIRMS satellite data, NOAA climate data, and potentially topography data for a specific region and time period.")
print("- **Proper Preprocessing:** Implement robust pipelines for atmospheric correction, georeferencing, handling missing values, and performing accurate spatial and temporal interpolation of all data sources.")
print("- **Incorporate Topography and Other Features:** Include actual elevation, slope, aspect, wind speed, humidity, and other relevant features in the dataset.")
print("- **Spatio-temporal Data Handling:** Explore data structures and modeling techniques that explicitly account for the spatial and temporal dependencies in the data (e.g., using xarray more extensively, or libraries for geospatial data).")
print("- **Explore Advanced Models:** Investigate more advanced models such as Convolutional Neural Networks (CNNs) for direct image analysis, Recurrent Neural Networks (RNNs) or LSTMs for temporal dependencies, or spatio-temporal models that integrate both.")
print("- **Refined Feature Engineering:** Develop more sophisticated methods for deriving features like fuel moisture using established models or methodologies.")
print("- **Spatio-temporal Cross-Validation:** Implement cross-validation strategies that respect the spatial and temporal structure of the data to get a more reliable estimate of model performance.")
print("- **Operationalize Prediction:** Develop a system to regularly acquire new data, run predictions, and visualize wildfire risk maps in near real-time.")
print("-" * 50)

Simulating loading satellite imagery...
Simulated MODIS imagery Dataset:

<xarray.Dataset> Size: 2MB
Dimensions:    (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time       (time) datetime64[ns] 80B 2022-01-01 2022-01-02 ... 2022-01-10
  * latitude   (latitude) float64 800B 32.0 32.1 32.2 32.3 ... 41.8 41.9 42.0
  * longitude  (longitude) float64 1kB -124.0 -123.9 -123.9 ... -114.1 -114.0
Data variables:
    red        (time, latitude, longitude) float64 1MB 0.2114 0.1183 ... 0.3997
    nir        (time, latitude, longitude) float64 1MB 0.3803 0.7149 ... 0.5323

Simulating loading weather data...
Simulated NOAA weather DataFrame:

        time   latitude   longitude  temperature  precipitation
0 2022-01-03  41.893340 -123.607553    20.638691       2.292648
1 2022-01-09  39.433688 -123.918907     1.708782       5.689219
2 2022-01-07  32.869528 -121.243817     5.585081       2.136602
3 2022-01-01  35.927868 -123.739624    25.723891       6.046510
4 2022-01-05  41.880531 -121.220098    10.300537       4.639086

Calculating NDVI...
Added NDVI to MODIS Dataset:

<xarray.Dataset> Size: 4MB
Dimensions:    (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time       (time) datetime64[ns] 80B 2022-01-01 2022-01-02 ... 2022-01-10
  * latitude   (latitude) float64 800B 32.0 32.1 32.2 32.3 ... 41.8 41.9 42.0
  * longitude  (longitude) float64 1kB -124.0 -123.9 -123.9 ... -114.1 -114.0
Data variables:
    red        (time, latitude, longitude) float64 1MB 0.2114 0.1183 ... 0.3997
    nir        (time, latitude, longitude) float64 1MB 0.3803 0.7149 ... 0.5323
    ndvi       (time, latitude, longitude) float64 1MB 0.2854 0.7161 ... 0.1423

Simulating cleaning and formatting weather data...
Simulated cleaned weather DataFrame:

        time   latitude   longitude  temperature  precipitation
0 2022-01-03  41.893340 -123.607553    20.638691       2.292648
1 2022-01-09  39.433688 -123.918907     1.708782       5.689219
2 2022-01-07  32.869528 -121.243817     5.585081       2.136602
3 2022-01-01  35.927868 -123.739624    25.723891       6.046510
4 2022-01-05  41.880531 -121.220098    10.300537       4.639086

Acknowledging the need for spatial and temporal interpolation of weather data...
In a real scenario, weather data would be interpolated to match the time, latitude, and longitude grid of the satellite imagery.
Simulated interpolated weather Dataset:

<xarray.Dataset> Size: 2MB
Dimensions:        (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time           (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude       (latitude) float64 800B 32.0 32.1 32.2 ... 41.8 41.9 42.0
  * longitude      (longitude) float64 1kB -124.0 -123.9 ... -114.1 -114.0
Data variables:
    temperature    (time, latitude, longitude) float64 1MB 4.496 12.51 ... 10.71
    precipitation  (time, latitude, longitude) float64 1MB 9.718 8.308 ... 2.68

Integrating satellite imagery and weather data...
Unified Dataset:

<xarray.Dataset> Size: 6MB
Dimensions:        (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time           (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude       (latitude) float64 800B 32.0 32.1 32.2 ... 41.8 41.9 42.0
  * longitude      (longitude) float64 1kB -124.0 -123.9 ... -114.1 -114.0
Data variables:
    red            (time, latitude, longitude) float64 1MB 0.2114 ... 0.3997
    nir            (time, latitude, longitude) float64 1MB 0.3803 ... 0.5323
    ndvi           (time, latitude, longitude) float64 1MB 0.2854 ... 0.1423
    temperature    (time, latitude, longitude) float64 1MB 4.496 12.51 ... 10.71
    precipitation  (time, latitude, longitude) float64 1MB 9.718 8.308 ... 2.68

Acknowledging the need for atmospheric correction and georeferencing...
In a real scenario, atmospheric correction would be applied to satellite imagery to remove atmospheric effects, and georeferencing would ensure accurate spatial alignment.
Simulating topography (elevation, slope, aspect), wind speed, and humidity...
Simulated topography, wind speed, and humidity added to unified Dataset.

Updated unified Dataset structure:

<xarray.Dataset> Size: 12MB
Dimensions:        (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time           (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude       (latitude) float64 800B 32.0 32.1 32.2 ... 41.8 41.9 42.0
  * longitude      (longitude) float64 1kB -124.0 -123.9 ... -114.1 -114.0
Data variables:
    red            (time, latitude, longitude) float64 1MB 0.2114 ... 0.3997
    nir            (time, latitude, longitude) float64 1MB 0.3803 ... 0.5323
    ndvi           (time, latitude, longitude) float64 1MB 0.2854 ... 0.1423
    temperature    (time, latitude, longitude) float64 1MB 4.496 12.51 ... 10.71
    precipitation  (time, latitude, longitude) float64 1MB 9.718 8.308 ... 2.68
    elevation      (time, latitude, longitude) float64 1MB 1.792e+03 ... 792.1
    slope          (time, latitude, longitude) float64 1MB 41.09 27.95 ... 11.41
    aspect         (time, latitude, longitude) float64 1MB 216.2 26.41 ... 202.0
    wind_speed     (time, latitude, longitude) float64 1MB 24.17 14.88 ... 21.01
    humidity       (time, latitude, longitude) float64 1MB 43.07 36.05 ... 65.62

Simulating adding historical fire data...
Added historical fire data to unified Dataset.

Acknowledging the importance of topography data...
Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.
Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.
This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.

Deriving a simulated fuel moisture index...
Added simulated fuel moisture index to unified Dataset.

Acknowledging other important features not present...
Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.

Updated unified Dataset structure:

<xarray.Dataset> Size: 14MB
Dimensions:                  (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time                     (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude                 (latitude) float64 800B 32.0 32.1 ... 41.9 42.0
  * longitude                (longitude) float64 1kB -124.0 -123.9 ... -114.0
Data variables:
    red                      (time, latitude, longitude) float64 1MB 0.2114 ....
    nir                      (time, latitude, longitude) float64 1MB 0.3803 ....
    ndvi                     (time, latitude, longitude) float64 1MB 0.2854 ....
    temperature              (time, latitude, longitude) float64 1MB 4.496 .....
    precipitation            (time, latitude, longitude) float64 1MB 9.718 .....
    elevation                (time, latitude, longitude) float64 1MB 1.792e+0...
    slope                    (time, latitude, longitude) float64 1MB 41.09 .....
    aspect                   (time, latitude, longitude) float64 1MB 216.2 .....
    wind_speed               (time, latitude, longitude) float64 1MB 24.17 .....
    humidity                 (time, latitude, longitude) float64 1MB 43.07 .....
    fire_history             (time, latitude, longitude) int64 1MB 1 1 0 ... 0 0
    simulated_fuel_moisture  (time, latitude, longitude) float64 1MB 17.68 .....

Shape of X_train: (105000, 11)
Shape of y_train: (105000,)
Shape of X_val: (22500, 11)
Shape of y_val: (22500,)
Shape of X_test: (22500, 11)
Shape of y_test: (22500,)
Retraining the Random Forest model on combined training and validation data...
Retraining complete.
Making predictions on the test set...
Predictions complete.

Calculating evaluation metrics on the test set...
Evaluation metrics calculated.

--- Model Evaluation Metrics (Test Set) ---
Precision: 0.5030
Recall: 0.4708
F1-Score: 0.4864
AUC-ROC: 0.5058
False Alarm Rate: 0.4650
-----------------------------------------
## 1. Data Sources
Due to the lack of direct access to real-world satellite imagery (MODIS, FIRMS) and environmental data (NOAA), the data used in this project was simulated.
- **MODIS/FIRMS Simulation:** Simulated raster data for 'red' and 'nir' bands were created using `xarray` with defined time, latitude, and longitude dimensions. Historical fire data was also simulated as a binary raster.
- **NOAA Data Simulation:** Simulated point data for 'temperature' and 'precipitation' were created using `pandas` DataFrames with time, latitude, and longitude columns.
- **Topography, Wind, Humidity Simulation:** Simulated raster data for 'elevation', 'slope', 'aspect', 'wind_speed', and 'humidity' were created and added to the `xarray` dataset.
It's important to note that these simulations do not capture the complexity, spatial heterogeneity, or temporal dynamics of real satellite and weather data.
--------------------------------------------------
## 2. Data Preprocessing Steps
The preprocessing steps were simulated to mimic a real-world workflow:
- **Simulated Loading and Cleaning:** Placeholder data structures (`xarray.Dataset` and `pandas.DataFrame`) were created to represent the raw data. Basic cleaning like dropping NaNs was mentioned but not extensively performed on the simulated data.
- **NDVI Calculation:** The Normalized Difference Vegetation Index (NDVI) was calculated from the simulated 'red' and 'nir' bands using the standard formula.
- **Atmospheric Correction and Georeferencing:** These crucial steps for real satellite imagery were acknowledged as necessary but not performed due to the simulated nature of the data. They would ensure accurate reflectance values and spatial alignment.
- **Simulated Weather Data Interpolation:** The need to interpolate point-based weather data (temperature, precipitation) to match the raster grid and time steps of the satellite imagery was acknowledged. A simulated interpolated weather dataset with the same dimensions as the imagery was created.
- **Data Integration:** The simulated satellite imagery (including NDVI) and the simulated interpolated weather data, along with simulated topography, wind, and humidity, were merged into a single `xarray.Dataset` for unified handling.
--------------------------------------------------
## 3. Feature Engineering Process
Features were engineered or included based on common practices in wildfire prediction:
- **Simulated Historical Fire Data:** A binary raster representing historical fire occurrences was simulated and added as a feature. This serves as a proxy for past fire activity, which is often a strong predictor.
- **Derived Simulated Fuel Moisture Index:** A simplified fuel moisture index was derived from the simulated temperature and precipitation data. This simulation used a basic formula and does not represent a scientifically accurate fuel moisture model. The importance of real fuel moisture models was noted.
- **Simulated Topography, Wind, and Humidity:** Simulated data for elevation, slope, aspect, wind speed, and humidity were generated and added as features.
--------------------------------------------------
## 4. Data Splitting Methodology
The unified dataset was converted from an xarray Dataset to a pandas DataFrame by stacking the spatial dimensions (latitude and longitude), treating each grid cell at each time step as a sample.
The data was then split into training, validation, and test sets using `sklearn.model_selection.train_test_split`:
- **Initial Split:** 70% Training, 30% Temporary (Validation + Test)
- **Second Split:** The 30% temporary set was further split into 50% Validation and 50% Test, resulting in approximately 15% Validation and 15% Test sets relative to the original data.
A `random_state` was used to ensure reproducibility of the splits.
--------------------------------------------------
## 5. Model Details and Training Process
- **Model Choice:** A Random Forest Classifier (`sklearn.ensemble.RandomForestClassifier`) was chosen for this binary classification task, suitable for predicting the probability of fire occurrence.
- **Parameters:** The model was instantiated with `n_estimators=100` (number of trees in the forest) and `random_state=42` for reproducibility. `n_jobs=-1` was used to utilize all available CPU cores for faster training speed.
- **Training Process:**
  - The model was initially trained on the `X_train` and `y_train` sets.
  - Following evaluation, the model was retrained on the combined `X_train_combined` and `y_train_combined` sets (training + validation data) for the final evaluation on the test set and prediction on new data.
--------------------------------------------------
## 6. Evaluation Results and Limitations
The model's performance was evaluated using standard classification metrics on both the validation and test sets.
The metrics obtained on the **Test Set** were:
- Precision: 0.5030
- Recall: 0.4708
- F1-Score: 0.4864
- AUC-ROC: 0.5058
- False Alarm Rate: 0.4650

**Limitations:**
- **Spatial and Temporal Accuracy:** Due to the data splitting method that flattened the spatial and temporal dimensions, specific spatial accuracy (e.g., correctly predicting fire location) and temporal accuracy (e.g., predicting fire timing) metrics could not be calculated in this workflow.
- **Simulated Data:** The metrics are based on simulated data, which may not reflect the model's performance on real-world data. The simulated features and target variable lack the complexity and real-world relationships present in actual wildfire datasets.
--------------------------------------------------
## 7. Wildfire Risk Prediction on New Data
The retrained model was used to predict wildfire risk probabilities on simulated new data.
- **New Data Simulation:** A DataFrame (`X_new`) with 100 samples was simulated, containing the same features as the training data ('red', 'nir', 'temperature', 'precipitation', 'simulated_fuel_moisture', 'elevation', 'slope', 'aspect', 'wind_speed', 'humidity').
- **Preprocessing:** NDVI was calculated for the simulated new data to ensure consistency with the training data features.
- **Prediction:** The `retrained_model.predict_proba()` method was used to obtain the probability of fire occurrence for each sample in the simulated new data.
The predicted probabilities were added as a new column ('predicted_fire_probability') to the `X_new` DataFrame.
--------------------------------------------------
## 8. Key Insights Gained
Even with simulated data, the process highlighted several key aspects:
- **Workflow Demonstration:** The exercise successfully demonstrated the end-to-end workflow of a machine learning project for environmental prediction, from data simulation and preprocessing to model training, evaluation, and prediction.
- **Feature Importance (Implicit):** While not explicitly analyzed, the chosen features (simulated satellite bands, NDVI, temperature, precipitation, fuel moisture, historical fire, topography, wind, humidity) represent commonly used indicators for wildfire risk, reinforcing their potential relevance in a real model.
- **Data Preparation Challenges:** The simulation underscored the complexity of preparing real-world geospatial and temporal data, particularly atmospheric correction, georeferencing, and spatio-temporal interpolation.
- **Evaluation Nuances:** The limitation in calculating spatial and temporal accuracy highlighted the importance of data structure and splitting strategies when working with spatio-temporal data.
- **Model Applicability:** A Random Forest Classifier, or similar tree-based models, are suitable baseline models for this type of tabular prediction task once the data is prepared.
--------------------------------------------------
## 9. Potential Next Steps for Real-World Implementation
To transition this project towards a real-world application, the following steps would be crucial:
- **Obtain Actual Data:** Secure access to and download real MODIS/FIRMS satellite data, NOAA climate data, and potentially topography data for a specific region and time period.
- **Proper Preprocessing:** Implement robust pipelines for atmospheric correction, georeferencing, handling missing values, and performing accurate spatial and temporal interpolation of all data sources.
- **Incorporate Topography and Other Features:** Include actual elevation, slope, aspect, wind speed, humidity, and other relevant features in the dataset.
- **Spatio-temporal Data Handling:** Explore data structures and modeling techniques that explicitly account for the spatial and temporal dependencies in the data (e.g., using xarray more extensively, or libraries for geospatial data).
- **Explore Advanced Models:** Investigate more advanced models such as Convolutional Neural Networks (CNNs) for direct image analysis, Recurrent Neural Networks (RNNs) or LSTMs for temporal dependencies, or spatio-temporal models that integrate both.
- **Refined Feature Engineering:** Develop more sophisticated methods for deriving features like fuel moisture using established models or methodologies.
- **Spatio-temporal Cross-Validation:** Implement cross-validation strategies that respect the spatial and temporal structure of the data to get a more reliable estimate of model performance.
- **Operationalize Prediction:** Develop a system to regularly acquire new data, run predictions, and visualize wildfire risk maps in near real-time.
--------------------------------------------------

## Wildfire risk prediction

### Subtask:
Use the trained and evaluated model to predict wildfire risk in new or unseen areas.

**Reasoning**:
Load or define new data for prediction, preprocess it similarly to training data, and use the retrained model to predict wildfire risk probabilities.

In [12]:
import pandas as pd
import numpy as np

# Step 1: Define or load the data for the new or unseen area.
# Since actual new data is not available, we will simulate new data
# with the same features as the training data.
print("Simulating new data for prediction...")

# Create a small sample of simulated new data
n_new_samples = 100
new_data = {
    'red': np.random.rand(n_new_samples) * 0.3 + 0.1,
    'nir': np.random.rand(n_new_samples) * 0.5 + 0.3,
    'temperature': np.random.uniform(0, 35, n_new_samples),
    'precipitation': np.random.uniform(0, 15, n_new_samples),
    'simulated_fuel_moisture': np.random.uniform(0, 100, n_new_samples),
    'elevation': np.random.uniform(100, 3000, n_new_samples), # Simulated elevation
    'slope': np.random.uniform(0, 45, n_new_samples), # Simulated slope
    'aspect': np.random.uniform(0, 360, n_new_samples), # Simulated aspect
    'wind_speed': np.random.uniform(0, 30, n_new_samples), # Simulated wind speed
    'humidity': np.random.uniform(20, 100, n_new_samples) # Simulated humidity
}
X_new = pd.DataFrame(new_data)

# Step 2: Ensure the new data is preprocessed in the same way.
# This includes calculating 'ndvi' if it's not directly provided.
# Check if 'ndvi' is in the new data, if not, calculate it.
if 'ndvi' not in X_new.columns:
    print("Calculating NDVI for new data...")
    # Calculate NDVI, ensuring no division by zero
    X_new['ndvi'] = (X_new['nir'] - X_new['red']) / (X_new['nir'] + X_new['red'] + 1e-9)

# Ensure the columns are in the same order as the training data features
# This is important for models like Random Forest.
features_order = ['red', 'nir', 'ndvi', 'temperature', 'precipitation', 'simulated_fuel_moisture', 'elevation', 'slope', 'aspect', 'wind_speed', 'humidity']
X_new = X_new[features_order]


print("New data simulated and preprocessed:")
display(X_new.head())

# Step 3: Use the retrained model to predict wildfire probability for the new data.
print("\nPredicting wildfire risk probabilities for new data...")
# Assuming 'retrained_model' is available from the previous step.
# Use predict_proba and select the probability for the positive class (fire=1).
new_area_wildfire_probabilities = retrained_model.predict_proba(X_new)[:, 1]
print("Prediction complete.")

# Step 4: Store the predicted wildfire risk probabilities.
# For this simulation, we'll store them in a pandas Series or add to the DataFrame.
# Let's add it as a new column to the new data DataFrame for easy viewing.
X_new['predicted_fire_probability'] = new_area_wildfire_probabilities

# Step 5: Display or visualize the predicted wildfire risk.
print("\nPredicted wildfire risk probabilities for the new data:")
display(X_new[['predicted_fire_probability']].head())

# If spatial/temporal information was available for new_data,
# a spatial risk map visualization would be ideal here.
print("\nNote: A spatial risk map could be generated if spatial coordinates were retained.")

Simulating new data for prediction...
Calculating NDVI for new data...
New data simulated and preprocessed:

,red,nir,ndvi,temperature,precipitation,simulated_fuel_moisture,elevation,slope,aspect,wind_speed,humidity
0,0.384237,0.331798,-0.073235,24.127849,6.469426,83.642121,152.645108,43.125707,212.228340,11.255093,65.328291
1,0.366768,0.514200,0.167352,33.317264,1.730573,26.414617,1583.704190,12.683368,146.299835,20.350114,58.683256
2,0.368526,0.694731,0.306798,30.361387,10.832298,11.802318,1997.557961,32.479745,295.956048,9.779419,97.351213
3,0.199357,0.601873,0.502372,7.835527,13.552601,13.338287,1572.258921,36.790875,228.114955,0.032982,92.584757
4,0.238615,0.566384,0.407167,31.069058,6.506805,55.994513,678.628234,43.042458,60.951102,17.373412,30.976445

Predicting wildfire risk probabilities for new data...
Prediction complete.

Predicted wildfire risk probabilities for the new data:

   predicted_fire_probability
0                        0.53
1                        0.46
2                        0.54
3                        0.35
4                        0.48

Note: A spatial risk map could be generated if spatial coordinates were retained.

## Model refinement and testing

### Subtask:
Fine-tune the models based on validation results and evaluate their performance on the unseen test set.

**Reasoning**:
Train the Random Forest model on the combined training and validation data, make predictions on the test set, calculate the evaluation metrics, and print them.

In [13]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# 1. Combine training and validation data
X_train_combined = pd.concat([X_train, X_val])
y_train_combined = pd.concat([y_train, y_val])

# Train the Random Forest Classifier model on the combined data
print("Retraining the Random Forest model on combined training and validation data...")
retrained_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
retrained_model.fit(X_train_combined, y_train_combined)
print("Retraining complete.")

# 2. Make predictions on the test set
print("Making predictions on the test set...")
y_test_pred_class = retrained_model.predict(X_test)
y_test_pred_proba = retrained_model.predict_proba(X_test)[:, 1] # Probability of the positive class (fire=1)
print("Predictions complete.")

# 3. Calculate evaluation metrics on the test set
print("\nCalculating evaluation metrics on the test set...")
precision = precision_score(y_test, y_test_pred_class)
recall = recall_score(y_test, y_test_pred_class)
f1 = f1_score(y_test, y_test_pred_class)
auc_roc = roc_auc_score(y_test, y_test_pred_proba)

# Calculate False Alarm Rate
conf_matrix = confusion_matrix(y_test, y_test_pred_class)
# conf_matrix structure: [[TN, FP], [FN, TP]]
TN, FP, FN, TP = conf_matrix.ravel()
false_alarm_rate = FP / (FP + TN)
print("Evaluation metrics calculated.")

# 4. Print the calculated evaluation metrics for the test set
print("\n--- Model Evaluation Metrics (Test Set) ---")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"AUC-ROC: {auc_roc:.4f}")
print(f"False Alarm Rate: {false_alarm_rate:.4f}")
print("-----------------------------------------")

# 5. Acknowledge the limitations regarding Spatial and Temporal accuracy
print("\nAcknowledging limitations:")
print("Spatial and Temporal accuracy metrics require re-associating predictions with original coordinates and time.")
print("Due to the data splitting method that flattened the spatial and temporal dimensions, these specific metrics are not calculated in this evaluation step.")

Retraining the Random Forest model on combined training and validation data...
Retraining complete.
Making predictions on the test set...
Predictions complete.

Calculating evaluation metrics on the test set...
Evaluation metrics calculated.

--- Model Evaluation Metrics (Test Set) ---
Precision: 0.5030
Recall: 0.4708
F1-Score: 0.4864
AUC-ROC: 0.5058
False Alarm Rate: 0.4650
-----------------------------------------

Acknowledging limitations:
Spatial and Temporal accuracy metrics require re-associating predictions with original coordinates and time.
Due to the data splitting method that flattened the spatial and temporal dimensions, these specific metrics are not calculated in this evaluation step.

## Model evaluation

### Subtask:
Evaluate the trained models using the specified metrics (Precision, Recall, F1-Score, AUC-ROC, Spatial accuracy, Temporal accuracy, False alarm rate) on the validation set.

**Reasoning**:
Calculate and print the evaluation metrics for the model on the validation set, excluding spatial and temporal accuracy as per instructions.

In [15]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# Add the code from cell 1c7fdca8 here
# 1. Choose a suitable machine learning model: Random Forest Classifier
# It's appropriate for tabular data and binary classification.

# 3. Instantiate the chosen model
model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
# Using 100 estimators as a reasonable starting point and random_state for reproducibility.
# n_jobs=-1 utilizes all available cores for faster training.

# 4. Train the model
print("Training the Random Forest model...")
model.fit(X_train, y_train)
print("Training complete.")

# 5. Make predictions on the validation set
print("Making predictions on the validation set...")
y_val_pred_class = model.predict(X_val)
y_val_pred_proba = model.predict_proba(X_val)[:, 1] # Get probability of the positive class (fire=1)
print("Predictions complete.")

print("\nFirst 10 predicted classes on validation set:", y_val_pred_class[:10])
print("First 10 predicted probabilities (of fire) on validation set:", y_val_pred_proba[:10])

# 2. Calculate Precision
precision = precision_score(y_val, y_val_pred_class)

# 3. Calculate Recall
recall = recall_score(y_val, y_val_pred_class)

# 4. Calculate F1-Score
f1 = f1_score(y_val, y_val_pred_class)

# 5. Calculate AUC-ROC
auc_roc = roc_auc_score(y_val, y_val_pred_proba)

# 6. Acknowledge Spatial and Temporal Accuracy (as per instructions)
print("Spatial and Temporal accuracy require re-associating predictions with original coordinates.")
print("Calculation of these metrics is not performed in this step due to the data splitting process.")

# 7. Calculate False Alarm Rate (False Positive Rate)
conf_matrix = confusion_matrix(y_val, y_val_pred_class)
# conf_matrix structure: [[TN, FP], [FN, TP]]
TN, FP, FN, TP = conf_matrix.ravel()
false_alarm_rate = FP / (FP + TN)

# 8. Print all calculated metrics
print("\n--- Model Evaluation Metrics (Validation Set) ---")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"AUC-ROC: {auc_roc:.4f}")
print(f"False Alarm Rate: {false_alarm_rate:.4f}")
print("-------------------------------------------------")

Training the Random Forest model...
Training complete.
Making predictions on the validation set...
Predictions complete.

First 10 predicted classes on validation set: [0 0 1 0 0 0 0 0 1 1]
First 10 predicted probabilities (of fire) on validation set: [0.42 0.5  0.58 0.45 0.44 0.44 0.39 0.39 0.56 0.57]
Spatial and Temporal accuracy require re-associating predictions with original coordinates.
Calculation of these metrics is not performed in this step due to the data splitting process.

--- Model Evaluation Metrics (Validation Set) ---
Precision: 0.5008
Recall: 0.4598
F1-Score: 0.4794
AUC-ROC: 0.4973
False Alarm Rate: 0.4664
-------------------------------------------------

## Model selection and development

### Subtask:
Choose appropriate models based on the data characteristics and the problem (e.g., CNNs for image analysis, Random Forest/XGBoost for risk prediction, LSTM for temporal patterns). Develop and train the selected models.

**Reasoning**:
Choose, instantiate, train, and make predictions with a Random Forest Classifier model on the training and validation data.

In [16]:
from sklearn.ensemble import RandomForestClassifier

# 1. Choose a suitable machine learning model: Random Forest Classifier
# It's appropriate for tabular data and binary classification.

# 3. Instantiate the chosen model
model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
# Using 100 estimators as a reasonable starting point and random_state for reproducibility.
# n_jobs=-1 utilizes all available cores for faster training.

# 4. Train the model
print("Training the Random Forest model...")
model.fit(X_train, y_train)
print("Training complete.")

# 5. Make predictions on the validation set
print("Making predictions on the validation set...")
y_val_pred_class = model.predict(X_val)
y_val_pred_proba = model.predict_proba(X_val)[:, 1] # Get probability of the positive class (fire=1)
print("Predictions complete.")

print("\nFirst 10 predicted classes on validation set:", y_val_pred_class[:10])
print("First 10 predicted probabilities (of fire) on validation set:", y_val_pred_proba[:10])

Training the Random Forest model...
Training complete.
Making predictions on the validation set...
Predictions complete.

First 10 predicted classes on validation set: [0 0 1 0 0 0 0 0 1 1]
First 10 predicted probabilities (of fire) on validation set: [0.42 0.5  0.58 0.45 0.44 0.44 0.39 0.39 0.56 0.57]

## Data splitting

### Subtask:
Split the dataset into training, validation, and testing sets for model development and evaluation.

**Reasoning**:
Import the necessary library for splitting the dataset, define features (X) and target (y) from the unified dataset, reshape them as needed, and then split the data into training, validation, and test sets. Finally, print the shapes of the resulting sets.

In [17]:
from sklearn.model_selection import train_test_split
import numpy as np

# Define features (X) and target (y)
# The target variable is 'fire_history'.
# Features are the remaining relevant variables.
features = ['red', 'nir', 'ndvi', 'temperature', 'precipitation', 'simulated_fuel_moisture', 'elevation', 'slope', 'aspect', 'wind_speed', 'humidity']
target = 'fire_history'

# Convert the xarray Dataset to a pandas DataFrame for easier handling with train_test_split
# We will stack the spatial dimensions (latitude, longitude) to treat each grid cell at each time step as a sample.
# This assumes a modeling approach where each time-location snapshot is an independent sample.
unified_df = unified_ds.to_dataframe().reset_index()

# Drop the 'time', 'latitude', and 'longitude' columns from features for splitting,
# as these define the sample index after stacking.
X = unified_df[features]
y = unified_df[target]

# Split the data into training and a temporary set (validation + test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Split the temporary set into validation and test sets
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

# Print the shapes of the resulting sets
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_val:", X_val.shape)
print("Shape of y_val:", y_val.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (105000, 11)
Shape of y_train: (105000,)
Shape of X_val: (22500, 11)
Shape of y_val: (22500,)
Shape of X_test: (22500, 11)
Shape of y_test: (22500,)

## Feature engineering

### Subtask:
Extract relevant features from the processed data. This could include historical fire data, topography (if available), and deriving new features like fuel moisture estimates from the existing data.

**Reasoning**:
Simulate adding historical fire data, acknowledge the lack of topography data, derive a simulated fuel moisture index, and acknowledge other missing features, finally displaying the updated dataset.

In [18]:
# Step 2: Simulate adding historical fire data as a new data variable to unified_ds.
print("Simulating adding historical fire data...")
# Create a placeholder data variable for historical fire occurrences.
# This could be a binary mask (0 for no fire, 1 for fire) or fire radiative power.
# We'll create a binary mask with some random fire occurrences.
fire_history_data = np.random.randint(0, 2, size=unified_ds['red'].shape)
unified_ds['fire_history'] = (('time', 'latitude', 'longitude'), fire_history_data)

print("Added historical fire data to unified Dataset.")

# Step 3: Acknowledge that topography data is crucial but not available.
print("\nAcknowledging the importance of topography data...")
print("Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.")
print("Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.")
print("This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.")

# Step 4: Derive a simulated fuel moisture index.
print("\nDeriving a simulated fuel moisture index...")
# Create a simplified placeholder calculation based on temperature and precipitation.
# A real fuel moisture model is complex and depends on various factors.
# This is a simple inverse relationship with temperature and direct with precipitation.
# Ensure no division by zero or undefined behavior with extreme values.
# Adding a small constant to the denominator and scaling to a plausible range (e.g., 0 to 100)
simulated_fuel_moisture = (unified_ds['precipitation'] * 10) / (unified_ds['temperature'] + 1 + 1e-9)
# Clip values to a reasonable range, e.g., 0 to 100 for a percentage-like index
simulated_fuel_moisture = np.clip(simulated_fuel_moisture, 0, 100)
# Extract the data using .data property as required by the error
unified_ds['simulated_fuel_moisture'] = (('time', 'latitude', 'longitude'), simulated_fuel_moisture.data)

print("Added simulated fuel moisture index to unified Dataset.")

# Step 5: Acknowledge other potentially relevant features.
print("\nAcknowledging other important features not present...")
print("Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.")

# Step 6: Ensure the newly engineered features are added as data variables to the unified_ds.
# This was done in steps 2 and 4 by assigning new data variables to unified_ds.

# Step 7: Display the structure of the updated unified_ds.
print("\nUpdated unified Dataset structure:")
display(unified_ds)

Simulating adding historical fire data...
Added historical fire data to unified Dataset.

Acknowledging the importance of topography data...
Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.
Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.
This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.

Deriving a simulated fuel moisture index...
Added simulated fuel moisture index to unified Dataset.

Acknowledging other important features not present...
Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.

Updated unified Dataset structure:

<xarray.Dataset> Size: 14MB
Dimensions:                  (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time                     (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude                 (latitude) float64 800B 32.0 32.1 ... 41.9 42.0
  * longitude                (longitude) float64 1kB -124.0 -123.9 ... -114.0
Data variables:
    red                      (time, latitude, longitude) float64 1MB 0.2114 ....
    nir                      (time, latitude, longitude) float64 1MB 0.3803 ....
    ndvi                     (time, latitude, longitude) float64 1MB 0.2854 ....
    temperature              (time, latitude, longitude) float64 1MB 4.496 .....
    precipitation            (time, latitude, longitude) float64 1MB 9.718 .....
    elevation                (time, latitude, longitude) float64 1MB 1.792e+0...
    slope                    (time, latitude, longitude) float64 1MB 41.09 .....
    aspect                   (time, latitude, longitude) float64 1MB 216.2 .....
    wind_speed               (time, latitude, longitude) float64 1MB 24.17 .....
    humidity                 (time, latitude, longitude) float64 1MB 43.07 .....
    fire_history             (time, latitude, longitude) int64 1MB 1 0 0 ... 1 0
    simulated_fuel_moisture  (time, latitude, longitude) float64 1MB 17.68 .....

In [19]:
import xarray as xr
import numpy as np

# Assuming 'unified_ds' from previous steps is available
# If not, we would need to recreate a placeholder unified_ds

print("Simulating topography (elevation, slope, aspect), wind speed, and humidity...")

# Simulate Elevation (example: a simple gradient or random noise)
# Real elevation would come from a DEM and be static over time.
# For simulation, we'll create a static 2D field and expand it over time.
elevation_data_2d = np.random.uniform(100, 3000, size=(unified_ds.sizes['latitude'], unified_ds.sizes['longitude']))
elevation_data = np.repeat(elevation_data_2d[np.newaxis, :, :], unified_ds.sizes['time'], axis=0)
unified_ds['elevation'] = (('time', 'latitude', 'longitude'), elevation_data)

# Simulate Slope and Aspect (derived from elevation in reality)
# For simulation, we'll just create random data.
# Slope: 0-90 degrees
slope_data = np.random.uniform(0, 45, size=unified_ds['elevation'].shape)
unified_ds['slope'] = (('time', 'latitude', 'longitude'), slope_data)

# Aspect: 0-360 degrees
aspect_data = np.random.uniform(0, 360, size=unified_ds['elevation'].shape)
unified_ds['aspect'] = (('time', 'latitude', 'longitude'), aspect_data)

# Simulate Wind Speed (example: random positive values)
wind_speed_data = np.random.uniform(0, 30, size=unified_ds['elevation'].shape) # knots or m/s
unified_ds['wind_speed'] = (('time', 'latitude', 'longitude'), wind_speed_data)

# Simulate Humidity (example: random values between 0 and 100)
humidity_data = np.random.uniform(20, 100, size=unified_ds['elevation'].shape) # percentage
unified_ds['humidity'] = (('time', 'latitude', 'longitude'), humidity_data)

print("Simulated topography, wind speed, and humidity added to unified Dataset.")

# Display the updated structure of the unified_ds
print("\nUpdated unified Dataset structure:")
display(unified_ds)

Simulating topography (elevation, slope, aspect), wind speed, and humidity...
Simulated topography, wind speed, and humidity added to unified Dataset.

Updated unified Dataset structure:

<xarray.Dataset> Size: 14MB
Dimensions:                  (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time                     (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude                 (latitude) float64 800B 32.0 32.1 ... 41.9 42.0
  * longitude                (longitude) float64 1kB -124.0 -123.9 ... -114.0
Data variables:
    red                      (time, latitude, longitude) float64 1MB 0.2114 ....
    nir                      (time, latitude, longitude) float64 1MB 0.3803 ....
    ndvi                     (time, latitude, longitude) float64 1MB 0.2854 ....
    temperature              (time, latitude, longitude) float64 1MB 4.496 .....
    precipitation            (time, latitude, longitude) float64 1MB 9.718 .....
    elevation                (time, latitude, longitude) float64 1MB 1.009e+0...
    slope                    (time, latitude, longitude) float64 1MB 8.353 .....
    aspect                   (time, latitude, longitude) float64 1MB 27.4 ......
    wind_speed               (time, latitude, longitude) float64 1MB 10.25 .....
    humidity                 (time, latitude, longitude) float64 1MB 21.7 ......
    fire_history             (time, latitude, longitude) int64 1MB 1 0 0 ... 1 0
    simulated_fuel_moisture  (time, latitude, longitude) float64 1MB 17.68 .....

### Exploring Missing Features: Topography

**Why is Topography Important for Wildfire Prediction?**

Topographical features significantly influence wildfire ignition and spread:

*   **Elevation:** Higher elevations can have different vegetation types, fuel moisture levels, and weather patterns compared to lower elevations.
*   **Slope:** Fires tend to spread more rapidly uphill because the flames preheat the fuel above them. Steeper slopes can lead to faster fire spread.
*   **Aspect:** The direction a slope faces (e.g., north-facing, south-facing) affects the amount of solar radiation it receives, which in turn impacts vegetation type, fuel moisture, and temperature. South-facing slopes in the Northern Hemisphere are typically drier and receive more direct sunlight, making them more prone to fire.

**How Would Topography Data Be Incorporated?**

In a real-world wildfire prediction model, topography data would typically be incorporated as follows:

1.  **Acquisition:** Obtain a Digital Elevation Model (DEM) for the study area. DEMs are readily available from sources like the USGS (for the United States) or other national mapping agencies.
2.  **Derived Features:** From the DEM, derive slope and aspect using geospatial analysis tools or libraries (e.g., GDAL, rasterio, ArcGIS, QGIS).
3.  **Alignment:** Resample or reproject the elevation, slope, and aspect data to match the spatial resolution and extent of your satellite imagery and weather data.
4.  **Integration:** Add the resampled elevation, slope, and aspect as new data variables to your unified dataset, ensuring they are aligned with the existing time, latitude, and longitude dimensions.

By including topography, your model would have access to crucial information about the terrain that significantly impacts wildfire behavior, leading to potentially more accurate predictions.

# Task
Develop a wildfire prediction model using satellite imagery and environmental data, following the provided problem statement, data sources, and evaluation metrics.

## Data acquisition

### Subtask:
Download or access the relevant satellite imagery (MODIS, FIRMS) and weather data (NOAA Climate Data) based on the geographical area and time period of interest.

**Reasoning**:
Explore the contents of the unzipped directory to identify relevant data files.

In [20]:
import os

unzip_destination = '/content/'

print(f"Listing files and directories in {unzip_destination}:")
for root, dirs, files in os.walk(unzip_destination):
    print(f"Directory: {root}")
    for file in files:
        print(f"  File: {file}")

Listing files and directories in /content/:
Directory: /content/
  File: Dataset.zip
Directory: /content/.config
  File: .last_survey_prompt.yaml
  File: config_sentinel
  File: gce
  File: .last_opt_in_prompt.yaml
  File: active_config
  File: default_configs.db
  File: hidden_gcloud_config_universe_descriptor_data_cache_configs.db
  File: .last_update_check.json
Directory: /content/.config/logs
Directory: /content/.config/logs/2025.10.10
  File: 13.35.51.839716.log
  File: 13.36.01.945525.log
  File: 13.36.10.325401.log
  File: 13.36.11.036806.log
  File: 13.35.31.347850.log
  File: 13.36.00.745649.log
Directory: /content/.config/configurations
  File: config_default
Directory: /content/sample_data
  File: anscombe.json
  File: README.md
  File: mnist_test.csv
  File: california_housing_test.csv
  File: mnist_train_small.csv
  File: california_housing_train.csv

**Reasoning**:
Based on the listing of files, the unzipped content does not appear to contain the specified satellite imagery or weather data. Therefore, the next step is to outline how to access MODIS, FIRMS, and NOAA Climate Data externally.

In [21]:
# Step 1: Identify the specific geographical area and time period for which you need wildfire data.
# For this example, let's assume the area is California, USA and the time period is 2022-2023.
geographical_area = "California, USA"
time_period = "2022-2023"

print(f"Identified Geographical Area: {geographical_area}")
print(f"Identified Time Period: {time_period}")

# Step 2 and 3: Explore contents of Dataset.zip and identify alternative data access methods.
# As seen from the previous output, Dataset.zip does not contain the required data.
# Therefore, we need to access MODIS, FIRMS, and NOAA Climate Data externally.

print("\nDataset.zip does not contain the required satellite imagery and weather data.")
print("Outlining alternative methods to access MODIS, FIRMS, and NOAA Climate Data:")

# Step 4: Outline steps for external data acquisition.

print("\nSteps for External Data Acquisition:")
print("1. Access MODIS data:")
print("   - Use the NASA Earthdata Search portal (search.earthdata.nasa.gov) to find relevant MODIS products (e.g., MOD14A1 for thermal anomalies/fire).")
print("   - Filter by the geographical area (California) and time period (2022-2023).")
print("   - Download the data in a suitable format (e.g., HDF or GeoTIFF). APIs like the Earthdata Search API could be used for automated access.")

print("\n2. Access FIRMS data:")
print("   - Use the NASA FIRMS (Fire Information for Resource Management System) website (firms.modaps.eosdis.nasa.gov) or their API.")
print("   - Select the area of interest (California) and time range (2022-2023).")
print("   - Download active fire data, typically available in CSV, shapefile, or KML formats.")

print("\n3. Access NOAA Climate Data:")
print("   - Use the NOAA National Centers for Environmental Information (NCEI) website (www.ncdc.noaa.gov/cdo-web/).")
print("   - Search for relevant climate data (e.g., temperature, precipitation, wind) for weather stations within or near California.")
print("   - Specify the time period (2022-2023).")
print("   - Download the data, often available in CSV format.")

print("\nChallenges and Considerations within Colab:")
print("- Data Size: Satellite imagery and climate data can be very large. Ensure sufficient storage space in the Colab environment or use Google Drive integration.")
print("- Access Restrictions: Some data portals or APIs might require registration or have download limits.")
print("- Data Processing: Large datasets may require efficient processing techniques (e.g., using libraries like xarray or dask) due to memory limitations in Colab.")
print("- Authentication: APIs may require API keys or authentication.")

Identified Geographical Area: California, USA
Identified Time Period: 2022-2023

Dataset.zip does not contain the required satellite imagery and weather data.
Outlining alternative methods to access MODIS, FIRMS, and NOAA Climate Data:

Steps for External Data Acquisition:
1. Access MODIS data:
   - Use the NASA Earthdata Search portal (search.earthdata.nasa.gov) to find relevant MODIS products (e.g., MOD14A1 for thermal anomalies/fire).
   - Filter by the geographical area (California) and time period (2022-2023).
   - Download the data in a suitable format (e.g., HDF or GeoTIFF). APIs like the Earthdata Search API could be used for automated access.

2. Access FIRMS data:
   - Use the NASA FIRMS (Fire Information for Resource Management System) website (firms.modaps.eosdis.nasa.gov) or their API.
   - Select the area of interest (California) and time range (2022-2023).
   - Download active fire data, typically available in CSV, shapefile, or KML formats.

3. Access NOAA Climate Data:
   - Use the NOAA National Centers for Environmental Information (NCEI) website (www.ncdc.noaa.gov/cdo-web/).
   - Search for relevant climate data (e.g., temperature, precipitation, wind) for weather stations within or near California.
   - Specify the time period (2022-2023).
   - Download the data, often available in CSV format.

Challenges and Considerations within Colab:
- Data Size: Satellite imagery and climate data can be very large. Ensure sufficient storage space in the Colab environment or use Google Drive integration.
- Access Restrictions: Some data portals or APIs might require registration or have download limits.
- Data Processing: Large datasets may require efficient processing techniques (e.g., using libraries like xarray or dask) due to memory limitations in Colab.
- Authentication: APIs may require API keys or authentication.

## Data preprocessing

### Subtask:
Process satellite imagery, weather data, and integrate them.

**Reasoning**:
The previous subtask confirmed that the necessary data is not in the provided zip file and outlined the steps for external data acquisition. Since direct external download within this environment is not feasible without further setup (API keys, registration, etc.), I will simulate the data loading step by creating placeholder data structures using `xarray` for satellite imagery and `pandas` for weather data, representing how the actual data would be loaded. This allows the subsequent steps of the subtask (processing and integration) to be demonstrated conceptually. I will then create placeholder vegetation index data and attempt to simulate the integration of these placeholder datasets.

In [22]:
import xarray as xr
import pandas as pd
import numpy as np

# Step 1: Simulate loading satellite imagery (MODIS) using xarray DataArray
# In a real scenario, you would use xr.open_dataset() or similar functions
# to load data from downloaded HDF or GeoTIFF files.
print("Simulating loading satellite imagery...")
# Create a placeholder DataArray representing MODIS imagery (e.g., Red and NIR bands)
# with dimensions for time, latitude, and longitude.
time_coords = pd.date_range('2022-01-01', periods=10, freq='D')
lat_coords = np.linspace(32, 42, 100) # Example latitude range for California
lon_coords = np.linspace(-124, -114, 150) # Example longitude range for California

# Create dummy data for Red and NIR bands
red_band_data = np.random.rand(10, 100, 150) * 0.3 + 0.1 # Example reflectance values
nir_band_data = np.random.rand(10, 100, 150) * 0.5 + 0.3 # Example reflectance values

modis_ds = xr.Dataset({
    'red': (['time', 'latitude', 'longitude'], red_band_data),
    'nir': (['time', 'latitude', 'longitude'], nir_band_data)
}, coords={'time': time_coords, 'latitude': lat_coords, 'longitude': lon_coords})

print("Simulated MODIS imagery Dataset:")
display(modis_ds)

# Step 1: Simulate loading weather data (NOAA) using pandas DataFrame
# In a real scenario, you would use pd.read_csv() or similar functions
# to load data from downloaded CSV files.
print("\nSimulating loading weather data...")
# Create a placeholder DataFrame representing weather data from multiple stations
# with columns for time, latitude, longitude, temperature, and precipitation.
weather_data = {
    'time': pd.to_datetime(np.random.choice(time_coords, 50)),
    'latitude': np.random.uniform(32, 42, 50),
    'longitude': np.random.uniform(-124, -114, 50),
    'temperature': np.random.uniform(0, 30, 50), # Example temperature in Celsius
    'precipitation': np.random.uniform(0, 10, 50) # Example precipitation in mm
}
weather_df = pd.DataFrame(weather_data)

print("Simulated NOAA weather DataFrame:")
display(weather_df.head())


# Step 3: Calculate relevant vegetation indices (NDVI) from the simulated satellite imagery
print("\nCalculating NDVI...")
# NDVI = (NIR - Red) / (NIR + Red)
# Ensure no division by zero by adding a small epsilon or handling NaNs
ndvi = (modis_ds['nir'] - modis_ds['red']) / (modis_ds['nir'] + modis_ds['red'] + 1e-9)
modis_ds['ndvi'] = ndvi

print("Added NDVI to MODIS Dataset:")
display(modis_ds)

# Step 4: Clean and format the weather data (Simulated)
# In a real scenario, this would involve handling missing values (e.g., imputation),
# standardizing column names, correcting data types, etc.
print("\nSimulating cleaning and formatting weather data...")
# For this simulation, we assume the data is already reasonably clean.
# A simple step like dropping potential NaNs could be done:
weather_df_cleaned = weather_df.dropna()

print("Simulated cleaned weather DataFrame:")
display(weather_df_cleaned.head())

# Step 5: Interpolate weather data spatially and temporally to match the satellite imagery resolution (Simulated)
# This is a complex step in a real scenario, often involving spatial interpolation
# techniques (e.g., inverse distance weighting, kriging) and temporal interpolation.
# For simulation purposes, we'll skip the actual interpolation and acknowledge the need.
print("\nAcknowledging the need for spatial and temporal interpolation of weather data...")
print("In a real scenario, weather data would be interpolated to match the time, latitude, and longitude grid of the satellite imagery.")
# The result would ideally be an xarray DataArray or Dataset with the same dimensions as modis_ds.
# Let's create a placeholder for the interpolated weather data with the same dimensions as modis_ds
interpolated_weather_ds = xr.Dataset({
    'temperature': (['time', 'latitude', 'longitude'], np.random.uniform(0, 30, size=modis_ds['red'].shape)),
    'precipitation': ((['time', 'latitude', 'longitude']), np.random.uniform(0, 10, size=modis_ds['red'].shape))
}, coords=modis_ds.coords)

print("Simulated interpolated weather Dataset:")
display(interpolated_weather_ds)


# Step 6: Integrate the processed satellite imagery and interpolated weather data into a unified dataset (Simulated)
print("\nIntegrating satellite imagery and weather data...")
# Combine the two xarray Datasets. Assuming they have the same dimensions and coordinates.
unified_ds = xr.merge([modis_ds, interpolated_weather_ds])

print("Unified Dataset:")
display(unified_ds)

# Step 2: Perform atmospheric correction and georeferencing (Acknowledged)
print("\nAcknowledging the need for atmospheric correction and georeferencing...")
print("In a real scenario, atmospheric correction would be applied to satellite imagery to remove atmospheric effects, and georeferencing would ensure accurate spatial alignment.")
# These steps are highly dependent on the specific data product and require specialized libraries
# or tools (e.g., GDAL, rasterio, or specific remote sensing software), which are not
# straightforward to demonstrate with placeholder data in this environment.

Simulating loading satellite imagery...
Simulated MODIS imagery Dataset:

<xarray.Dataset> Size: 2MB
Dimensions:    (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time       (time) datetime64[ns] 80B 2022-01-01 2022-01-02 ... 2022-01-10
  * latitude   (latitude) float64 800B 32.0 32.1 32.2 32.3 ... 41.8 41.9 42.0
  * longitude  (longitude) float64 1kB -124.0 -123.9 -123.9 ... -114.1 -114.0
Data variables:
    red        (time, latitude, longitude) float64 1MB 0.1195 0.3049 ... 0.1868
    nir        (time, latitude, longitude) float64 1MB 0.779 0.667 ... 0.3093

Simulating loading weather data...
Simulated NOAA weather DataFrame:

        time   latitude   longitude  temperature  precipitation
0 2022-01-04  40.660401 -123.332087     9.078604       7.940859
1 2022-01-01  41.226459 -118.989524     4.565112       6.358547
2 2022-01-01  34.918968 -121.405756     1.197836       6.091158
3 2022-01-07  34.463323 -118.264218     4.623989       8.996207
4 2022-01-06  34.793339 -122.704333    10.568409       7.442050

Calculating NDVI...
Added NDVI to MODIS Dataset:

<xarray.Dataset> Size: 4MB
Dimensions:    (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time       (time) datetime64[ns] 80B 2022-01-01 2022-01-02 ... 2022-01-10
  * latitude   (latitude) float64 800B 32.0 32.1 32.2 32.3 ... 41.8 41.9 42.0
  * longitude  (longitude) float64 1kB -124.0 -123.9 -123.9 ... -114.1 -114.0
Data variables:
    red        (time, latitude, longitude) float64 1MB 0.1195 0.3049 ... 0.1868
    nir        (time, latitude, longitude) float64 1MB 0.779 0.667 ... 0.3093
    ndvi       (time, latitude, longitude) float64 1MB 0.7339 0.3725 ... 0.247

Simulating cleaning and formatting weather data...
Simulated cleaned weather DataFrame:

        time   latitude   longitude  temperature  precipitation
0 2022-01-04  40.660401 -123.332087     9.078604       7.940859
1 2022-01-01  41.226459 -118.989524     4.565112       6.358547
2 2022-01-01  34.918968 -121.405756     1.197836       6.091158
3 2022-01-07  34.463323 -118.264218     4.623989       8.996207
4 2022-01-06  34.793339 -122.704333    10.568409       7.442050

Acknowledging the need for spatial and temporal interpolation of weather data...
In a real scenario, weather data would be interpolated to match the time, latitude, and longitude grid of the satellite imagery.
Simulated interpolated weather Dataset:

<xarray.Dataset> Size: 2MB
Dimensions:        (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time           (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude       (latitude) float64 800B 32.0 32.1 32.2 ... 41.8 41.9 42.0
  * longitude      (longitude) float64 1kB -124.0 -123.9 ... -114.1 -114.0
Data variables:
    temperature    (time, latitude, longitude) float64 1MB 16.1 26.4 ... 15.92
    precipitation  (time, latitude, longitude) float64 1MB 8.162 0.3806 ... 2.19

Integrating satellite imagery and weather data...
Unified Dataset:

<xarray.Dataset> Size: 6MB
Dimensions:        (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time           (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude       (latitude) float64 800B 32.0 32.1 32.2 ... 41.8 41.9 42.0
  * longitude      (longitude) float64 1kB -124.0 -123.9 ... -114.1 -114.0
Data variables:
    red            (time, latitude, longitude) float64 1MB 0.1195 ... 0.1868
    nir            (time, latitude, longitude) float64 1MB 0.779 ... 0.3093
    ndvi           (time, latitude, longitude) float64 1MB 0.7339 ... 0.247
    temperature    (time, latitude, longitude) float64 1MB 16.1 26.4 ... 15.92
    precipitation  (time, latitude, longitude) float64 1MB 8.162 0.3806 ... 2.19

Acknowledging the need for atmospheric correction and georeferencing...
In a real scenario, atmospheric correction would be applied to satellite imagery to remove atmospheric effects, and georeferencing would ensure accurate spatial alignment.

## Feature engineering

### Subtask:
Extract relevant features from the processed data. This could include historical fire data, topography (if available), and deriving new features like fuel moisture estimates from the existing data.

**Reasoning**:
Simulate adding historical fire data, acknowledge the lack of topography data, derive a simulated fuel moisture index, and acknowledge other missing features, finally displaying the updated dataset.

In [24]:
# Step 2: Simulate adding historical fire data as a new data variable to unified_ds.
print("Simulating adding historical fire data...")
# Create a placeholder data variable for historical fire occurrences.
# This could be a binary mask (0 for no fire, 1 for fire) or fire radiative power.
# We'll create a binary mask with some random fire occurrences.
fire_history_data = np.random.randint(0, 2, size=unified_ds['red'].shape)
unified_ds['fire_history'] = (('time', 'latitude', 'longitude'), fire_history_data)

print("Added historical fire data to unified Dataset.")

# Step 3: Acknowledge that topography data is crucial but not available.
print("\nAcknowledging the importance of topography data...")
print("Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.")
print("Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.")
print("This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.")

# Step 4: Derive a simulated fuel moisture index.
print("\nDeriving a simulated fuel moisture index...")
# Create a simplified placeholder calculation based on temperature and precipitation.
# A real fuel moisture model is complex and depends on various factors.
# This is a simple inverse relationship with temperature and direct with precipitation.
# Ensure no division by zero or undefined behavior with extreme values.
# Adding a small constant to the denominator and scaling to a plausible range (e.g., 0 to 100)
simulated_fuel_moisture = (unified_ds['precipitation'] * 10) / (unified_ds['temperature'] + 1 + 1e-9)
# Clip values to a reasonable range, e.g., 0 to 100 for a percentage-like index
simulated_fuel_moisture = np.clip(simulated_fuel_moisture, 0, 100)
# Extract the data using .data property as required by the error
unified_ds['simulated_fuel_moisture'] = (('time', 'latitude', 'longitude'), simulated_fuel_moisture.data)

print("Added simulated fuel moisture index to unified Dataset.")

# Step 5: Acknowledge other potentially relevant features.
print("\nAcknowledging other important features not present...")
print("Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.")

# Step 6: Ensure the newly engineered features are added as data variables to the unified_ds.
# This was done in steps 2 and 4 by assigning new data variables to the unified_ds.

# Step 7: Display the structure of the updated unified_ds.
print("\nUpdated unified Dataset structure:")
display(unified_ds)

Simulating adding historical fire data...
Added historical fire data to unified Dataset.

Acknowledging the importance of topography data...
Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.
Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.
This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.

Deriving a simulated fuel moisture index...
Added simulated fuel moisture index to unified Dataset.

Acknowledging other important features not present...
Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.

Updated unified Dataset structure:

<xarray.Dataset> Size: 8MB
Dimensions:                  (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time                     (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude                 (latitude) float64 800B 32.0 32.1 ... 41.9 42.0
  * longitude                (longitude) float64 1kB -124.0 -123.9 ... -114.0
Data variables:
    red                      (time, latitude, longitude) float64 1MB 0.1195 ....
    nir                      (time, latitude, longitude) float64 1MB 0.779 .....
    ndvi                     (time, latitude, longitude) float64 1MB 0.7339 ....
    temperature              (time, latitude, longitude) float64 1MB 16.1 ......
    precipitation            (time, latitude, longitude) float64 1MB 8.162 .....
    fire_history             (time, latitude, longitude) int64 1MB 0 0 0 ... 0 0
    simulated_fuel_moisture  (time, latitude, longitude) float64 1MB 4.773 .....

**Reasoning**:
The previous code failed because it tried to assign a DataArray directly as a variable. I need to extract the data using the `.data` property when creating the new variable.

In [25]:
# Step 2: Simulate adding historical fire data as a new data variable to unified_ds.
print("Simulating adding historical fire data...")
# Create a placeholder data variable for historical fire occurrences.
# This could be a binary mask (0 for no fire, 1 for fire) or fire radiative power.
# We'll create a binary mask with some random fire occurrences.
fire_history_data = np.random.randint(0, 2, size=unified_ds['red'].shape)
unified_ds['fire_history'] = (('time', 'latitude', 'longitude'), fire_history_data)

print("Added historical fire data to unified Dataset.")

# Step 3: Acknowledge that topography data is crucial but not available.
print("\nAcknowledging the importance of topography data...")
print("Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.")
print("Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.")
print("This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.")

# Step 4: Derive a simulated fuel moisture index.
print("\nDeriving a simulated fuel moisture index...")
# Create a simplified placeholder calculation based on temperature and precipitation.
# A real fuel moisture model is complex and depends on various factors.
# This is a simple inverse relationship with temperature and direct with precipitation.
# Ensure no division by zero or undefined behavior with extreme values.
# Adding a small constant to the denominator and scaling to a plausible range (e.g., 0 to 100)
simulated_fuel_moisture = (unified_ds['precipitation'] * 10) / (unified_ds['temperature'] + 1 + 1e-9)
# Clip values to a reasonable range, e.g., 0 to 100 for a percentage-like index
simulated_fuel_moisture = np.clip(simulated_fuel_moisture, 0, 100)
# Extract the data using .data property as required by the error
unified_ds['simulated_fuel_moisture'] = (('time', 'latitude', 'longitude'), simulated_fuel_moisture.data)

print("Added simulated fuel moisture index to unified Dataset.")

# Step 5: Acknowledge other potentially relevant features.
print("\nAcknowledging other important features not present...")
print("Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.")

# Step 6: Ensure the newly engineered features are added as data variables to the unified_ds.
# This was done in steps 2 and 4 by assigning new data variables to unified_ds.

# Step 7: Display the structure of the updated unified_ds.
print("\nUpdated unified Dataset structure:")
display(unified_ds)

Simulating adding historical fire data...
Added historical fire data to unified Dataset.

Acknowledging the importance of topography data...
Topography data (elevation, slope, aspect) is crucial for wildfire prediction as it influences fire spread.
Ideally, this data would be incorporated as additional data variables in the unified_ds, aligned with the existing dimensions.
This would typically involve acquiring a Digital Elevation Model (DEM) and deriving slope and aspect from it, then resampling/aligning it to the unified_ds grid.

Deriving a simulated fuel moisture index...
Added simulated fuel moisture index to unified Dataset.

Acknowledging other important features not present...
Other features like wind speed, wind direction, and humidity are also important for wildfire prediction and would ideally be included if available in the weather data.

Updated unified Dataset structure:

<xarray.Dataset> Size: 8MB
Dimensions:                  (time: 10, latitude: 100, longitude: 150)
Coordinates:
  * time                     (time) datetime64[ns] 80B 2022-01-01 ... 2022-01-10
  * latitude                 (latitude) float64 800B 32.0 32.1 ... 41.9 42.0
  * longitude                (longitude) float64 1kB -124.0 -123.9 ... -114.0
Data variables:
    red                      (time, latitude, longitude) float64 1MB 0.1195 ....
    nir                      (time, latitude, longitude) float64 1MB 0.779 .....
    ndvi                     (time, latitude, longitude) float64 1MB 0.7339 ....
    temperature              (time, latitude, longitude) float64 1MB 16.1 ......
    precipitation            (time, latitude, longitude) float64 1MB 8.162 .....
    fire_history             (time, latitude, longitude) int64 1MB 1 1 1 ... 0 1
    simulated_fuel_moisture  (time, latitude, longitude) float64 1MB 4.773 .....

## Data splitting

### Subtask:
Split the dataset into training, validation, and testing sets for model development and evaluation.

**Reasoning**:
Import the necessary library for splitting the dataset, define features (X) and target (y) from the unified dataset, reshape them as needed, and then split the data into training, validation, and test sets. Finally, print the shapes of the resulting sets.

In [26]:
from sklearn.model_selection import train_test_split
import numpy as np

# Define features (X) and target (y)
# The target variable is 'fire_history'.
# Features are the remaining relevant variables.
features = ['red', 'nir', 'ndvi', 'temperature', 'precipitation', 'simulated_fuel_moisture']
target = 'fire_history'

# Convert the xarray Dataset to a pandas DataFrame for easier handling with train_test_split
# We will stack the spatial dimensions (latitude, longitude) to treat each grid cell at each time step as a sample.
# This assumes a modeling approach where each time-location snapshot is an independent sample.
unified_df = unified_ds.to_dataframe().reset_index()

# Drop the 'time', 'latitude', and 'longitude' columns from features for splitting,
# as these define the sample index after stacking.
X = unified_df[features]
y = unified_df[target]

# Split the data into training and a temporary set (validation + test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Split the temporary set into validation and test sets
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

# Print the shapes of the resulting sets
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_val:", X_val.shape)
print("Shape of y_val:", y_val.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (105000, 6)
Shape of y_train: (105000,)
Shape of X_val: (22500, 6)
Shape of y_val: (22500,)
Shape of X_test: (22500, 6)
Shape of y_test: (22500,)

## Model selection and development

### Subtask:
Choose appropriate models based on the data characteristics and the problem (e.g., CNNs for image analysis, Random Forest/XGBoost for risk prediction, LSTM for temporal patterns). Develop and train the selected models.

**Reasoning**:
Choose, instantiate, train, and make predictions with a Random Forest Classifier model on the training and validation data.

In [27]:
from sklearn.ensemble import RandomForestClassifier

# 1. Choose a suitable machine learning model: Random Forest Classifier
# It's appropriate for tabular data and binary classification.

# 3. Instantiate the chosen model
model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
# Using 100 estimators as a reasonable starting point and random_state for reproducibility.
# n_jobs=-1 utilizes all available cores for faster training.

# 4. Train the model
print("Training the Random Forest model...")
model.fit(X_train, y_train)
print("Training complete.")

# 5. Make predictions on the validation set
print("Making predictions on the validation set...")
y_val_pred_class = model.predict(X_val)
y_val_pred_proba = model.predict_proba(X_val)[:, 1] # Get probability of the positive class (fire=1)
print("Predictions complete.")

print("\nFirst 10 predicted classes on validation set:", y_val_pred_class[:10])
print("First 10 predicted probabilities (of fire) on validation set:", y_val_pred_proba[:10])

Training the Random Forest model...
Training complete.
Making predictions on the validation set...
Predictions complete.

First 10 predicted classes on validation set: [1 1 0 1 0 0 1 1 0 1]
First 10 predicted probabilities (of fire) on validation set: [0.68 0.72 0.5  0.57 0.5  0.4  0.54 0.64 0.41 0.61]

## Model evaluation

### Subtask:
Evaluate the trained models using the specified metrics (Precision, Recall, F1-Score, AUC-ROC, Spatial accuracy, Temporal accuracy, False alarm rate) on the validation set.

**Reasoning**:
Calculate and print the evaluation metrics for the model on the validation set, excluding spatial and temporal accuracy as per instructions.

In [28]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# 2. Calculate Precision
precision = precision_score(y_val, y_val_pred_class)

# 3. Calculate Recall
recall = recall_score(y_val, y_val_pred_class)

# 4. Calculate F1-Score
f1 = f1_score(y_val, y_val_pred_class)

# 5. Calculate AUC-ROC
auc_roc = roc_auc_score(y_val, y_val_pred_proba)

# 6. Acknowledge Spatial and Temporal Accuracy (as per instructions)
print("Spatial and Temporal accuracy require re-associating predictions with original coordinates.")
print("Calculation of these metrics is not performed in this step due to the data splitting process.")

# 7. Calculate False Alarm Rate (False Positive Rate)
conf_matrix = confusion_matrix(y_val, y_val_pred_class)
# conf_matrix structure: [[TN, FP], [FN, TP]]
TN, FP, FN, TP = conf_matrix.ravel()
false_alarm_rate = FP / (FP + TN)

# 8. Print all calculated metrics
print("\n--- Model Evaluation Metrics (Validation Set) ---")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"AUC-ROC: {auc_roc:.4f}")
print(f"False Alarm Rate: {false_alarm_rate:.4f}")
print("-------------------------------------------------")

Spatial and Temporal accuracy require re-associating predictions with original coordinates.
Calculation of these metrics is not performed in this step due to the data splitting process.

--- Model Evaluation Metrics (Validation Set) ---
Precision: 0.4935
Recall: 0.4736
F1-Score: 0.4834
AUC-ROC: 0.4907
False Alarm Rate: 0.4893
-------------------------------------------------

## Model refinement and testing

### Subtask:
Fine-tune the models based on validation results and evaluate their performance on the unseen test set.

**Reasoning**:
Train the Random Forest model on the combined training and validation data, make predictions on the test set, calculate the evaluation metrics, and print them.

In [29]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# 1. Combine training and validation data
X_train_combined = pd.concat([X_train, X_val])
y_train_combined = pd.concat([y_train, y_val])

# Train the Random Forest Classifier model on the combined data
print("Retraining the Random Forest model on combined training and validation data...")
retrained_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
retrained_model.fit(X_train_combined, y_train_combined)
print("Retraining complete.")

# 2. Make predictions on the test set
print("Making predictions on the test set...")
y_test_pred_class = retrained_model.predict(X_test)
y_test_pred_proba = retrained_model.predict_proba(X_test)[:, 1] # Probability of the positive class (fire=1)
print("Predictions complete.")

# 3. Calculate evaluation metrics on the test set
print("\nCalculating evaluation metrics on the test set...")
precision = precision_score(y_test, y_test_pred_class)
recall = recall_score(y_test, y_test_pred_class)
f1 = f1_score(y_test, y_test_pred_class)
auc_roc = roc_auc_score(y_test, y_test_pred_proba)

# Calculate False Alarm Rate
conf_matrix = confusion_matrix(y_test, y_test_pred_class)
# conf_matrix structure: [[TN, FP], [FN, TP]]
TN, FP, FN, TP = conf_matrix.ravel()
false_alarm_rate = FP / (FP + TN)
print("Evaluation metrics calculated.")

# 4. Print the calculated evaluation metrics for the test set
print("\n--- Model Evaluation Metrics (Test Set) ---")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"AUC-ROC: {auc_roc:.4f}")
print(f"False Alarm Rate: {false_alarm_rate:.4f}")
print("-----------------------------------------")

# 5. Acknowledge the limitations regarding Spatial and Temporal accuracy
print("\nAcknowledging limitations:")
print("Spatial and Temporal accuracy metrics require re-associating predictions with original coordinates and time.")
print("Due to the data splitting method that flattened the spatial and temporal dimensions, these specific metrics are not calculated in this evaluation step.")

Retraining the Random Forest model on combined training and validation data...
Retraining complete.
Making predictions on the test set...
Predictions complete.

Calculating evaluation metrics on the test set...
Evaluation metrics calculated.

--- Model Evaluation Metrics (Test Set) ---
Precision: 0.5026
Recall: 0.4788
F1-Score: 0.4904
AUC-ROC: 0.4997
False Alarm Rate: 0.4811
-----------------------------------------

Acknowledging limitations:
Spatial and Temporal accuracy metrics require re-associating predictions with original coordinates and time.
Due to the data splitting method that flattened the spatial and temporal dimensions, these specific metrics are not calculated in this evaluation step.

## Wildfire risk prediction

### Subtask:
Use the trained and evaluated model to predict wildfire risk in new or unseen areas.

**Reasoning**:
Load or define new data for prediction, preprocess it similarly to training data, and use the retrained model to predict wildfire risk probabilities.

In [30]:
import pandas as pd
import numpy as np

# Step 1: Define or load the data for the new or unseen area.
# Since actual new data is not available, we will simulate new data
# with the same features as the training data.
print("Simulating new data for prediction...")

# Create a small sample of simulated new data
n_new_samples = 100
new_data = {
    'red': np.random.rand(n_new_samples) * 0.3 + 0.1,
    'nir': np.random.rand(n_new_samples) * 0.5 + 0.3,
    'temperature': np.random.uniform(0, 35, n_new_samples),
    'precipitation': np.random.uniform(0, 15, n_new_samples),
    'simulated_fuel_moisture': np.random.uniform(0, 100, n_new_samples)
}
X_new = pd.DataFrame(new_data)

# Step 2: Ensure the new data is preprocessed in the same way.
# This includes calculating 'ndvi' if it's not directly provided.
# Check if 'ndvi' is in the new data, if not, calculate it.
if 'ndvi' not in X_new.columns:
    print("Calculating NDVI for new data...")
    # Calculate NDVI, ensuring no division by zero
    X_new['ndvi'] = (X_new['nir'] - X_new['red']) / (X_new['nir'] + X_new['red'] + 1e-9)

# Ensure the columns are in the same order as the training data features
# This is important for models like Random Forest.
features_order = ['red', 'nir', 'ndvi', 'temperature', 'precipitation', 'simulated_fuel_moisture']
X_new = X_new[features_order]

print("New data simulated and preprocessed:")
display(X_new.head())

# Step 3: Use the retrained model to predict wildfire probability for the new data.
print("\nPredicting wildfire risk probabilities for new data...")
# Assuming 'retrained_model' is available from the previous step.
# Use predict_proba and select the probability for the positive class (fire=1).
new_area_wildfire_probabilities = retrained_model.predict_proba(X_new)[:, 1]
print("Prediction complete.")

# Step 4: Store the predicted wildfire risk probabilities.
# For this simulation, we'll store them in a pandas Series or add to the DataFrame.
# Let's add it as a new column to the new data DataFrame for easy viewing.
X_new['predicted_fire_probability'] = new_area_wildfire_probabilities

# Step 5: Display or visualize the predicted wildfire risk.
print("\nPredicted wildfire risk probabilities for the new data:")
display(X_new[['predicted_fire_probability']].head())

# If spatial/temporal information was available for new_data,
# a spatial risk map visualization would be ideal here.
print("\nNote: A spatial risk map could be generated if spatial coordinates were retained.")

Simulating new data for prediction...
Calculating NDVI for new data...
New data simulated and preprocessed:

,red,nir,ndvi,temperature,precipitation,simulated_fuel_moisture
0,0.233453,0.590985,0.433667,29.099965,5.901765,11.969263
1,0.227891,0.785353,0.550176,6.120021,14.504869,54.838356
2,0.154551,0.479773,0.512706,34.463106,11.604498,68.931729
3,0.275657,0.385383,0.165989,24.329721,6.586118,50.166192
4,0.214501,0.588966,0.466062,28.221979,10.416911,65.134316

Predicting wildfire risk probabilities for new data...
Prediction complete.

Predicted wildfire risk probabilities for the new data:

   predicted_fire_probability
0                        0.56
1                        0.50
2                        0.44
3                        0.46
4                        0.32

Note: A spatial risk map could be generated if spatial coordinates were retained.

## Reporting

### Subtask:
Document the entire process, including data sources, preprocessing steps, model details, evaluation results, and insights gained.

**Reasoning**:
Document the entire process as requested in the subtask instructions, summarizing the steps performed and the insights gained based on the available variables and the context of simulated data.

In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import xarray as xr

# 1. Summarize Data Sources
print("## 1. Data Sources")
print("Due to the lack of direct access to real-world satellite imagery (MODIS, FIRMS) and environmental data (NOAA), the data used in this project was simulated.")
print("- **MODIS/FIRMS Simulation:** Simulated raster data for 'red' and 'nir' bands were created using `xarray` with defined time, latitude, and longitude dimensions. Historical fire data was also simulated as a binary raster.")
print("- **NOAA Data Simulation:** Simulated point data for 'temperature' and 'precipitation' were created using `pandas` DataFrames with time, latitude, and longitude columns.")
print("It's important to note that these simulations do not capture the complexity, spatial heterogeneity, or temporal dynamics of real satellite and weather data.")
print("-" * 50)

# 2. Detail Data Preprocessing Steps
print("## 2. Data Preprocessing Steps")
print("The preprocessing steps were simulated to mimic a real-world workflow:")
print("- **Simulated Loading and Cleaning:** Placeholder data structures (`xarray.Dataset` and `pandas.DataFrame`) were created to represent the raw data. Basic cleaning like dropping NaNs was mentioned but not extensively performed on the simulated data.")
print("- **NDVI Calculation:** The Normalized Difference Vegetation Index (NDVI) was calculated from the simulated 'red' and 'nir' bands using the standard formula.")
print("- **Atmospheric Correction and Georeferencing:** These crucial steps for real satellite imagery were acknowledged as necessary but not performed due to the simulated nature of the data. They would ensure accurate reflectance values and spatial alignment.")
print("- **Simulated Weather Data Interpolation:** The need to interpolate point-based weather data (temperature, precipitation) to match the raster grid and time steps of the satellite imagery was acknowledged. A simulated interpolated weather dataset with the same dimensions as the imagery was created.")
print("- **Data Integration:** The simulated satellite imagery (including NDVI) and the simulated interpolated weather data were merged into a single `xarray.Dataset` for unified handling.")
print("-" * 50)

# 3. Describe Feature Engineering Process
print("## 3. Feature Engineering Process")
print("Features were engineered or included based on common practices in wildfire prediction:")
print("- **Simulated Historical Fire Data:** A binary raster representing historical fire occurrences was simulated and added as a feature. This serves as a proxy for past fire activity, which is often a strong predictor.")
print("- **Derived Simulated Fuel Moisture Index:** A simplified fuel moisture index was derived from the simulated temperature and precipitation data. This simulation used a basic formula and does not represent a scientifically accurate fuel moisture model. The importance of real fuel moisture models was noted.")
print("- **Acknowledged Missing Features:** The critical role of topography (elevation, slope, aspect) and other weather features (wind speed, humidity) in wildfire behavior was acknowledged, highlighting their absence in this simulated dataset.")
print("-" * 50)

# 4. Explain Data Splitting Methodology
print("## 4. Data Splitting Methodology")
print("The unified dataset was converted from an xarray Dataset to a pandas DataFrame by stacking the spatial dimensions (latitude and longitude), treating each time-location snapshot as an independent sample.")
print("The data was then split into training, validation, and test sets using `sklearn.model_selection.train_test_split`:")
print(f"- **Initial Split:** 70% Training, 30% Temporary (Validation + Test)")
print(f"- **Second Split:** The 30% temporary set was further split into 50% Validation and 50% Test, resulting in approximately 15% Validation and 15% Test sets relative to the original data.")
print("A `random_state` was used to ensure reproducibility of the splits.")
print("-" * 50)

# 5. Provide Model Details and Training Process
print("## 5. Model Details and Training Process")
print("- **Model Choice:** A Random Forest Classifier (`sklearn.ensemble.RandomForestClassifier`) was chosen for this binary classification task, suitable for predicting the probability of fire occurrence.")
print("- **Parameters:** The model was instantiated with `n_estimators=100` (number of trees in the forest) and `random_state=42` for reproducibility. `n_jobs=-1` was used to utilize all available CPU cores for training speed.")
print("- **Training Process:**")
print("  - The model was initially trained on the `X_train` and `y_train` sets.")
print("  - Following evaluation, the model was retrained on the combined `X_train_combined` and `y_train_combined` sets (training + validation data) for the final evaluation on the test set and prediction on new data.")
print("-" * 50)

# 6. Present Evaluation Results and Limitations
print("## 6. Evaluation Results and Limitations")
print("The model's performance was evaluated using standard classification metrics on both the validation and test sets.")
print("The metrics obtained on the **Test Set** were:")
print(f"- Precision: {precision:.4f}")
print(f"- Recall: {recall:.4f}")
print(f"- F1-Score: {f1:.4f}")
print(f"- AUC-ROC: {auc_roc:.4f}")
print(f"- False Alarm Rate: {false_alarm_rate:.4f}")
print("\n**Limitations:**")
print("- **Spatial and Temporal Accuracy:** Due to the data splitting method that flattened the spatial and temporal dimensions, specific spatial accuracy (e.g., correctly predicting fire location) and temporal accuracy (e.g., predicting fire timing) metrics could not be calculated in this workflow.")
print("- **Simulated Data:** The metrics are based on simulated data, which may not reflect the model's performance on real-world data. The simulated features and target variable lack the complexity and real-world relationships present in actual wildfire datasets.")
print("-" * 50)

# 7. Summarize Wildfire Risk Prediction Step
print("## 7. Wildfire Risk Prediction on New Data")
print("The retrained model was used to predict wildfire risk probabilities on simulated new data.")
print(f"- **New Data Simulation:** A DataFrame (`X_new`) with {n_new_samples} samples was simulated, containing the same features as the training data ('red', 'nir', 'temperature', 'precipitation', 'simulated_fuel_moisture').")
print("- **Preprocessing:** NDVI was calculated for the simulated new data to ensure consistency with the training data features.")
print("- **Prediction:** The `retrained_model.predict_proba()` method was used to obtain the probability of fire occurrence for each sample in the simulated new data.")
print("The predicted probabilities were added as a new column ('predicted_fire_probability') to the `X_new` DataFrame.")
print("-" * 50)

# 8. Discuss Key Insights Gained
print("## 8. Key Insights Gained")
print("Even with simulated data, the process highlighted several key aspects:")
print("- **Workflow Demonstration:** The exercise successfully demonstrated the end-to-end workflow of a machine learning project for environmental prediction, from data simulation and preprocessing to model training, evaluation, and prediction.")
print("- **Feature Importance (Implicit):** While not explicitly analyzed, the chosen features (simulated satellite bands, NDVI, temperature, precipitation, fuel moisture, historical fire) represent commonly used indicators for wildfire risk, reinforcing their potential relevance in a real model.")
print("- **Data Preparation Challenges:** The simulation underscored the complexity of preparing real-world geospatial and temporal data, particularly atmospheric correction, georeferencing, and spatio-temporal interpolation.")
print("- **Evaluation Nuances:** The limitation in calculating spatial and temporal accuracy highlighted the importance of data structure and splitting strategies when working with spatio-temporal data.")
print("- **Model Applicability:** A Random Forest Classifier, or similar tree-based models, are suitable baseline models for this type of tabular prediction task once the data is prepared.")
print("-" * 50)

# 9. Outline Potential Next Steps for Real-World Implementation
print("## 9. Potential Next Steps for Real-World Implementation")
print("To transition this project towards a real-world application, the following steps would be crucial:")
print("- **Obtain Actual Data:** Secure access to and download real MODIS/FIRMS satellite data, NOAA climate data, and potentially topography data for a specific region and time period.")
print("- **Proper Preprocessing:** Implement robust pipelines for atmospheric correction, georeferencing, handling missing values, and performing accurate spatial and temporal interpolation of all data sources.")
print("- **Incorporate Topography and Other Features:** Include actual elevation, slope, aspect, wind speed, humidity, and other relevant features in the dataset.")
print("- **Spatio-temporal Data Handling:** Explore data structures and modeling techniques that explicitly account for the spatial and temporal dependencies in the data (e.g., using xarray more extensively, or libraries for geospatial data).")
print("- **Explore Advanced Models:** Investigate more advanced models such as Convolutional Neural Networks (CNNs) for direct image analysis, Recurrent Neural Networks (RNNs) or LSTMs for temporal dependencies, or spatio-temporal models that integrate both.")
print("- **Refined Feature Engineering:** Develop more sophisticated methods for deriving features like fuel moisture using established models or methodologies.")
print("- **Spatio-temporal Cross-Validation:** Implement cross-validation strategies that respect the spatial and temporal structure of the data to get a more reliable estimate of model performance.")
print("- **Operationalize Prediction:** Develop a system to regularly acquire new data, run predictions, and visualize wildfire risk maps in near real-time.")
print("-" * 50)

## 1. Data Sources
Due to the lack of direct access to real-world satellite imagery (MODIS, FIRMS) and environmental data (NOAA), the data used in this project was simulated.
- **MODIS/FIRMS Simulation:** Simulated raster data for 'red' and 'nir' bands were created using `xarray` with defined time, latitude, and longitude dimensions. Historical fire data was also simulated as a binary raster.
- **NOAA Data Simulation:** Simulated point data for 'temperature' and 'precipitation' were created using `pandas` DataFrames with time, latitude, and longitude columns.
It's important to note that these simulations do not capture the complexity, spatial heterogeneity, or temporal dynamics of real satellite and weather data.
--------------------------------------------------
## 2. Data Preprocessing Steps
The preprocessing steps were simulated to mimic a real-world workflow:
- **Simulated Loading and Cleaning:** Placeholder data structures (`xarray.Dataset` and `pandas.DataFrame`) were created to represent the raw data. Basic cleaning like dropping NaNs was mentioned but not extensively performed on the simulated data.
- **NDVI Calculation:** The Normalized Difference Vegetation Index (NDVI) was calculated from the simulated 'red' and 'nir' bands using the standard formula.
- **Atmospheric Correction and Georeferencing:** These crucial steps for real satellite imagery were acknowledged as necessary but not performed due to the simulated nature of the data. They would ensure accurate reflectance values and spatial alignment.
- **Simulated Weather Data Interpolation:** The need to interpolate point-based weather data (temperature, precipitation) to match the raster grid and time steps of the satellite imagery was acknowledged. A simulated interpolated weather dataset with the same dimensions as the imagery was created.
- **Data Integration:** The simulated satellite imagery (including NDVI) and the simulated interpolated weather data were merged into a single `xarray.Dataset` for unified handling.
--------------------------------------------------
## 3. Feature Engineering Process
Features were engineered or included based on common practices in wildfire prediction:
- **Simulated Historical Fire Data:** A binary raster representing historical fire occurrences was simulated and added as a feature. This serves as a proxy for past fire activity, which is often a strong predictor.
- **Derived Simulated Fuel Moisture Index:** A simplified fuel moisture index was derived from the simulated temperature and precipitation data. This simulation used a basic formula and does not represent a scientifically accurate fuel moisture model. The importance of real fuel moisture models was noted.
- **Acknowledged Missing Features:** The critical role of topography (elevation, slope, aspect) and other weather features (wind speed, humidity) in wildfire behavior was acknowledged, highlighting their absence in this simulated dataset.
--------------------------------------------------
## 4. Data Splitting Methodology
The unified dataset was converted from an xarray Dataset to a pandas DataFrame by stacking the spatial dimensions (latitude and longitude), treating each time-location snapshot as an independent sample.
The data was then split into training, validation, and test sets using `sklearn.model_selection.train_test_split`:
- **Initial Split:** 70% Training, 30% Temporary (Validation + Test)
- **Second Split:** The 30% temporary set was further split into 50% Validation and 50% Test, resulting in approximately 15% Validation and 15% Test sets relative to the original data.
A `random_state` was used to ensure reproducibility of the splits.
--------------------------------------------------
## 5. Model Details and Training Process
- **Model Choice:** A Random Forest Classifier (`sklearn.ensemble.RandomForestClassifier`) was chosen for this binary classification task, suitable for predicting the probability of fire occurrence.
- **Parameters:** The model was instantiated with `n_estimators=100` (number of trees in the forest) and `random_state=42` for reproducibility. `n_jobs=-1` was used to utilize all available CPU cores for training speed.
- **Training Process:**
  - The model was initially trained on the `X_train` and `y_train` sets.
  - Following evaluation, the model was retrained on the combined `X_train_combined` and `y_train_combined` sets (training + validation data) for the final evaluation on the test set and prediction on new data.
--------------------------------------------------
## 6. Evaluation Results and Limitations
The model's performance was evaluated using standard classification metrics on both the validation and test sets.
The metrics obtained on the **Test Set** were:
- Precision: 0.5026
- Recall: 0.4788
- F1-Score: 0.4904
- AUC-ROC: 0.4997
- False Alarm Rate: 0.4811

**Limitations:**
- **Spatial and Temporal Accuracy:** Due to the data splitting method that flattened the spatial and temporal dimensions, specific spatial accuracy (e.g., correctly predicting fire location) and temporal accuracy (e.g., predicting fire timing) metrics could not be calculated in this workflow.
- **Simulated Data:** The metrics are based on simulated data, which may not reflect the model's performance on real-world data. The simulated features and target variable lack the complexity and real-world relationships present in actual wildfire datasets.
--------------------------------------------------
## 7. Wildfire Risk Prediction on New Data
The retrained model was used to predict wildfire risk probabilities on simulated new data.
- **New Data Simulation:** A DataFrame (`X_new`) with 100 samples was simulated, containing the same features as the training data ('red', 'nir', 'temperature', 'precipitation', 'simulated_fuel_moisture').
- **Preprocessing:** NDVI was calculated for the simulated new data to ensure consistency with the training data features.
- **Prediction:** The `retrained_model.predict_proba()` method was used to obtain the probability of fire occurrence for each sample in the simulated new data.
The predicted probabilities were added as a new column ('predicted_fire_probability') to the `X_new` DataFrame.
--------------------------------------------------
## 8. Key Insights Gained
Even with simulated data, the process highlighted several key aspects:
- **Workflow Demonstration:** The exercise successfully demonstrated the end-to-end workflow of a machine learning project for environmental prediction, from data simulation and preprocessing to model training, evaluation, and prediction.
- **Feature Importance (Implicit):** While not explicitly analyzed, the chosen features (simulated satellite bands, NDVI, temperature, precipitation, fuel moisture, historical fire) represent commonly used indicators for wildfire risk, reinforcing their potential relevance in a real model.
- **Data Preparation Challenges:** The simulation underscored the complexity of preparing real-world geospatial and temporal data, particularly atmospheric correction, georeferencing, and spatio-temporal interpolation.
- **Evaluation Nuances:** The limitation in calculating spatial and temporal accuracy highlighted the importance of data structure and splitting strategies when working with spatio-temporal data.
- **Model Applicability:** A Random Forest Classifier, or similar tree-based models, are suitable baseline models for this type of tabular prediction task once the data is prepared.
--------------------------------------------------
## 9. Potential Next Steps for Real-World Implementation
To transition this project towards a real-world application, the following steps would be crucial:
- **Obtain Actual Data:** Secure access to and download real MODIS/FIRMS satellite data, NOAA climate data, and potentially topography data for a specific region and time period.
- **Proper Preprocessing:** Implement robust pipelines for atmospheric correction, georeferencing, handling missing values, and performing accurate spatial and temporal interpolation of all data sources.
- **Incorporate Topography and Other Features:** Include actual elevation, slope, aspect, wind speed, humidity, and other relevant features in the dataset.
- **Spatio-temporal Data Handling:** Explore data structures and modeling techniques that explicitly account for the spatial and temporal dependencies in the data (e.g., using xarray more extensively, or libraries for geospatial data).
- **Explore Advanced Models:** Investigate more advanced models such as Convolutional Neural Networks (CNNs) for direct image analysis, Recurrent Neural Networks (RNNs) or LSTMs for temporal dependencies, or spatio-temporal models that integrate both.
- **Refined Feature Engineering:** Develop more sophisticated methods for deriving features like fuel moisture using established models or methodologies.
- **Spatio-temporal Cross-Validation:** Implement cross-validation strategies that respect the spatial and temporal structure of the data to get a more reliable estimate of model performance.
- **Operationalize Prediction:** Develop a system to regularly acquire new data, run predictions, and visualize wildfire risk maps in near real-time.
--------------------------------------------------

## Summary:

### Data Analysis Key Findings

*   The initial attempt to use a provided `Dataset.zip` for data acquisition failed as it did not contain the necessary satellite imagery or weather data.
*   The project proceeded by simulating data using `xarray` for satellite imagery (MODIS) and `pandas` for weather data (NOAA). This simulation included creating placeholder data for red and near-infrared bands, temperature, precipitation, and historical fire occurrences.
*   Key preprocessing steps were simulated, including the calculation of the Normalized Difference Vegetation Index (NDVI) from the simulated satellite bands. The necessity of real-world steps like atmospheric correction, georeferencing, and spatio-temporal interpolation of weather data was acknowledged.
*   Feature engineering involved adding simulated historical fire data and a derived simulated fuel moisture index to the dataset. The critical absence of topography data and other weather variables like wind and humidity was noted.
*   The simulated spatio-temporal dataset was converted into a tabular format (DataFrame) by stacking spatial dimensions for compatibility with standard machine learning models like `scikit-learn`.
*   The tabular data was split into simulated training (70%), validation (15%), and test (15%) sets using `train_test_split`.
*   A Random Forest Classifier was chosen, trained on the simulated training data, and subsequently retrained on the combined training and validation data.
*   Model performance was evaluated on the simulated test set using standard classification metrics: Precision (0.4913), Recall (0.4815), F1-Score (0.4863), AUC-ROC (0.4979), and False Alarm Rate (0.4841). These metrics are based on simulated data and likely do not reflect real-world performance.
*   The inability to calculate spatial and temporal accuracy metrics due to the data splitting method (flattening spatio-temporal dimensions) was a significant limitation highlighted during evaluation.
*   The retrained model was successfully used to predict wildfire risk probabilities on simulated new data, demonstrating the prediction step of the workflow.
*   The entire simulated process, from data sources to prediction and evaluation limitations, was documented as a blueprint for a real-world implementation.

### Insights or Next Steps

*   A crucial next step for a real-world application is to obtain actual satellite imagery (MODIS, FIRMS), weather data (NOAA), and topography data for the target region and implement robust preprocessing pipelines including atmospheric correction, georeferencing, and accurate spatio-temporal interpolation.
*   Future model development should explore techniques and data structures (e.g., using `xarray` more fully, or specialized geospatial libraries) that preserve the spatio-temporal relationships in the data, enabling the calculation of spatial and temporal accuracy metrics and potentially leveraging spatial/temporal dependencies in the modeling process itself (e.g., Spatio-Temporal models, CNN-LSTM hybrids).